import json
import re

exercises = []

# --- MODULE 18 : Prologue, Épilogue & Sub-Registers ---
exercises.extend([
    {"id": "ex-mod18-1", "type": "quiz", "question": "Quelle est la règle d'or concernant l'écriture dans un registre 32-bits (ex: EAX) sur une architecture x86-64 ?", "difficulty": "easy", "xpReward": 20, "data": {"choices": [{"id": "a", "text": "Les 32 bits supérieurs de RAX restent intacts."}, {"id": "b", "text": "Les 32 bits supérieurs de RAX sont automatiquement mis à zéro."}, {"id": "c", "text": "Cela provoque une erreur de compilation."}], "correctId": "b", "explanation": "Pour éviter un 'partial register stall', le CPU efface toujours la moitié supérieure de RAX lorsqu'on écrit dans EAX."}},
    {"id": "ex-mod18-2", "type": "quiz", "question": "Quelle paire de registres est utilisée pour stocker le résultat massif de 128-bits d'une multiplication 64-bits (`mul`) ?", "difficulty": "easy", "xpReward": 20, "data": {"choices": [{"id": "a", "text": "RCX et R8"}, {"id": "b", "text": "RAX et RBX"}, {"id": "c", "text": "RDX et RAX (RDX:RAX)"}], "correctId": "c", "explanation": "L'instruction `mul` met implicitement les bits de poids fort dans RDX et les bits de poids faible dans RAX."}},
    {"id": "ex-mod18-3", "type": "quiz", "question": "Dans le prologue standard d'une fonction, à quoi sert `push rbp` suivi de `mov rbp, rsp` ?", "difficulty": "medium", "xpReward": 30, "data": {"choices": [{"id": "a", "text": "À appeler le Kernel."}, {"id": "b", "text": "À créer une 'Stack Frame' stable pour accéder facilement aux variables locales et paramètres."}, {"id": "c", "text": "À nettoyer les registres."}], "correctId": "b", "explanation": "RBP sert de point d'ancrage fixe (Base Pointer) pendant toute l'exécution de la fonction, car RSP peut bouger."}},
    {"id": "ex-mod18-4", "type": "fill-blank", "question": "L'Épilogue Rapide", "difficulty": "medium", "xpReward": 35, "data": {"codeTemplate": "; Au lieu de :\n; mov rsp, rbp\n; pop rbp\n; On peut utiliser l'instruction équivalente :\n__BLANK__", "blanks": [{"id": "1", "answer": "leave", "hint": "Quitter (en anglais)."}], "explanation": "L'instruction 'leave' restaure exactement RSP et RBP avant le retour."}},
    {"id": "ex-mod18-5", "type": "quiz", "question": "Quelle est la différence entre les instructions de saut `ja` et `jg` ?", "difficulty": "medium", "xpReward": 30, "data": {"choices": [{"id": "a", "text": "`ja` est pour les entiers Non-Signés, `jg` pour les entiers Signés."}, {"id": "b", "text": "`ja` saute en avant, `jg` saute en arrière."}, {"id": "c", "text": "Il n'y a aucune différence."}], "correctId": "a", "explanation": "Jump Above (`ja`) vérifie le Carry Flag (Non-Signé). Jump Greater (`jg`) vérifie l'Overflow Flag et le Sign Flag (Signé)."}},
    {"id": "ex-mod18-6", "type": "quiz", "question": "Pourquoi préfère-t-on souvent utiliser un 'Conditional Move' (cmov) plutôt qu'un saut conditionnel (je, jne) ?", "difficulty": "hard", "xpReward": 50, "data": {"choices": [{"id": "a", "text": "Parce qu'il évite de casser le pipeline d'instructions en cas de mauvaise prédiction de branchement."}, {"id": "b", "text": "Parce qu'il consomme moins de mémoire."}, {"id": "c", "text": "Parce qu'il peut exécuter deux sauts en même temps."}], "correctId": "a", "explanation": "Le Branch Misprediction coûte environ 15-20 cycles CPU. Le cmov est exécuté inconditionnellement, préservant la vitesse."}},
    {"id": "ex-mod18-7", "type": "drag-drop", "question": "Étapes de l'appel d'une fonction (Caller/Callee)", "difficulty": "hard", "xpReward": 50, "data": {"items": [{"id": "1", "text": "Mettre les arguments dans RDI, RSI (Caller)"}, {"id": "2", "text": "Instruction CALL (pousse RIP sur la pile)"}, {"id": "3", "text": "Prologue de la fonction (push rbp; mov rbp, rsp)"}, {"id": "4", "text": "Épilogue et RET (pop RIP)"}], "correctOrder": ["1", "2", "3", "4"], "instruction": "Ordonnez les étapes chronologiques d'un appel complet.", "explanation": "C'est la danse classique de la pile d'exécution en x86-64."}},
    {"id": "ex-mod18-8", "type": "fill-blank", "question": "Les divisions capricieuses", "difficulty": "hard", "xpReward": 50, "data": {"codeTemplate": "; Avant de faire un 'div rbx' (division de RAX par RBX),\n; il faut absolument mettre à zéro le registre supérieur __BLANK__\nmov __BLANK__, 0\ndiv rbx", "blanks": [{"id": "1", "answer": "rdx", "hint": "Le même registre utilisé par 'mul'."}, {"id": "2", "answer": "rdx", "hint": "Idem."}], "explanation": "L'instruction `div` prend le dividende combiné RDX:RAX. Si RDX contient des ordures (Garbages), le programme plantera (Floating Point Exception)."}},
    {"id": "ex-mod18-9", "type": "quiz", "question": "À quoi sert l'instruction `lea` (Load Effective Address) en dehors de la manipulation de pointeurs ?", "difficulty": "hard", "xpReward": 50, "data": {"choices": [{"id": "a", "text": "À faire des mathématiques rapides (additions/multiplications) en un seul cycle sans affecter les flags."}, {"id": "b", "text": "À appeler l'OS."}, {"id": "c", "text": "À déréférencer un pointeur NULL."}], "correctId": "a", "explanation": "Exemple : `lea rax, [rbx + rcx*4]` calcule une valeur mathématique purement arithmétique et la stocke dans RAX ultra rapidement."}},
    {"id": "ex-mod18-10", "type": "code-correction", "question": "Nettoyer un registre", "difficulty": "hard", "xpReward": 50, "data": {"buggyCode": "mov rax, 0", "correctCode": "xor eax, eax", "hints": ["L'opération logique XOR est la plus efficace pour mettre à zéro."], "explanation": "`xor eax, eax` est la norme : il prend moins d'octets en mémoire (2 octets) et brise les dépendances dans le CPU, le rendant plus rapide qu'un simple `mov`."}}
])

# --- MODULE 19 : Format ELF & Sections ---
exercises.extend([
    {"id": "ex-mod19-1", "type": "quiz", "question": "Dans quelle section du format ELF place-t-on le code exécutable (les instructions machine) ?", "difficulty": "easy", "xpReward": 20, "data": {"choices": [{"id": "a", "text": ".data"}, {"id": "b", "text": ".text"}, {"id": "c", "text": ".bss"}], "correctId": "b", "explanation": "La section `.text` contient les instructions CPU en lecture seule et exécution seule."}},
    {"id": "ex-mod19-2", "type": "quiz", "question": "Quelle section est utilisée pour les variables globales INITIALISÉES (ex: my_var = 42) ?", "difficulty": "easy", "xpReward": 20, "data": {"choices": [{"id": "a", "text": ".rodata"}, {"id": "b", "text": ".bss"}, {"id": "c", "text": ".data"}], "correctId": "c", "explanation": "La section `.data` contient les variables globales modifiables ayant une valeur de départ."}},
    {"id": "ex-mod19-3", "type": "quiz", "question": "Quel est l'avantage de la section `.bss` pour les grosses variables non-initialisées (ex: un tableau de 10 Mo) ?", "difficulty": "medium", "xpReward": 30, "data": {"choices": [{"id": "a", "text": "Elle n'occupe aucune place dans le fichier exécutable sur le disque dur."}, {"id": "b", "text": "Elle s'exécute plus vite."}, {"id": "c", "text": "Elle chiffre les données."}], "correctId": "a", "explanation": "L'OS alloue cette RAM au lancement du programme et la remplit de zéros. Le fichier binaire reste petit."}},
    {"id": "ex-mod19-4", "type": "fill-blank", "question": "Erreur de Segmentation", "difficulty": "medium", "xpReward": 35, "data": {"codeTemplate": "section __BLANK__\n  hello db 'Hello', 0\n\nsection .text\n  ; Tenter de modifier le 'H' de 'Hello'\n  mov byte [hello], 'J' ; ---> SEGFAULT !", "blanks": [{"id": "1", "answer": ".rodata", "hint": "Read-Only Data"}], "explanation": "L'OS protège la section .rodata en lecture seule via la MMU. Toute tentative d'écriture déclenche une faute matérielle."}},
    {"id": "ex-mod19-5", "type": "quiz", "question": "Qui a la responsabilité de charger les différentes sections en RAM et d'appeler le point d'entrée (_start) ?", "difficulty": "medium", "xpReward": 30, "data": {"choices": [{"id": "a", "text": "Le compilateur GCC."}, {"id": "b", "text": "Le chargeur (Loader) du noyau du système d'exploitation (OS)."}, {"id": "c", "text": "Le BIOS."}], "correctId": "b", "explanation": "C'est la fonction du système d'exploitation (execve) de parser le fichier ELF, d'allouer la mémoire et de céder le contrôle au programme."}},
    {"id": "ex-mod19-6", "type": "quiz", "question": "Comment le noyau (Kernel) fournit-il les arguments en ligne de commande (argc, argv) lors du lancement via `_start` ?", "difficulty": "hard", "xpReward": 50, "data": {"choices": [{"id": "a", "text": "Ils sont déposés magiquement dans les registres RDI et RSI."}, {"id": "b", "text": "Ils sont posés directement au sommet de la pile (Stack), pointés par RSP."}, {"id": "c", "text": "Ils sont écrits dans un fichier temporaire."}], "correctId": "b", "explanation": "Contrairement à la fonction main() du C (qui prend rdi et rsi), l'entrée native `_start` commence avec RSP pointant directement sur la valeur numérique `argc`."}},
    {"id": "ex-mod19-7", "type": "drag-drop", "question": "Sections Mémoire d'un Processus", "difficulty": "hard", "xpReward": 50, "data": {"items": [{"id": "1", "text": "Code (.text) (Adresses basses)"}, {"id": "2", "text": "Données Globales (.data / .bss)"}, {"id": "3", "text": "Tas (Heap) (Grandit vers le haut)"}, {"id": "4", "text": "Pile (Stack) (Grandit vers le bas, Adresses hautes)"}], "correctOrder": ["1", "2", "3", "4"], "instruction": "Classez les segments mémoire d'un processus classique Linux (de l'adresse 0 vers l'adresse haute).", "explanation": "Le Heap et la Stack se font face et grandissent l'un vers l'autre au centre de la RAM virtuelle."}},
    {"id": "ex-mod19-8", "type": "fill-blank", "question": "Directives de taille", "difficulty": "hard", "xpReward": 50, "data": {"codeTemplate": "section .bss\n  ; Réserver 100 octets (bytes) non initialisés\n  buffer __BLANK__ 100\n  \n  ; Réserver 10 quadwords (80 octets) non initialisés\n  pointers __BLANK__ 10", "blanks": [{"id": "1", "answer": "resb", "hint": "Reserve Byte."}, {"id": "2", "answer": "resq", "hint": "Reserve Quadword (64-bit)."}], "explanation": "La syntaxe NASM/YASM utilise `resb`, `resw`, `resd`, `resq` pour réserver de l'espace dans le `.bss` sans l'allouer dans le fichier."}},
    {"id": "ex-mod19-9", "type": "quiz", "question": "Que contient l'en-tête (Header) d'un fichier ELF ?", "difficulty": "hard", "xpReward": 50, "data": {"choices": [{"id": "a", "text": "Le code source du programme compressé en ZIP."}, {"id": "b", "text": "Les numéros magiques (Magic Bytes), l'architecture cible, et les adresses de chargement de chaque section."}, {"id": "c", "text": "Un dictionnaire Python."}], "correctId": "b", "explanation": "Le Loader utilise cet en-tête comme un 'plan de montage' pour savoir comment cartographier le fichier en RAM."}},
    {"id": "ex-mod19-10", "type": "code-correction", "question": "L'oubli fatal", "difficulty": "hard", "xpReward": 50, "data": {"buggyCode": "global main\n\nsection .text\nmain:\n  mov rax, 42\n  ret", "correctCode": "global _start\n\nsection .text\n_start:\n  mov rax, 42\n  ; Il faut un Syscall EXIT, car _start ne peut pas utiliser 'ret'", "hints": ["L'entrée pure d'un ELF s'appelle _start, et on n'a nulle part où 'retourner' (ret)."], "explanation": "Si on compile sans la libc (`nostdlib`), il faut utiliser `_start` et on ne peut PAS faire de `ret` car personne ne nous a appelé via `call`. Il faut faire un syscall `exit`."}}
])

# --- MODULE 20 : L'Appel Système ---
exercises.extend([
    {"id": "ex-mod20-1", "type": "quiz", "question": "Quel registre contient le numéro du service système (ex: 1 pour sys_write) avant d'appeler l'OS sous Linux 64-bits ?", "difficulty": "easy", "xpReward": 20, "data": {"choices": [{"id": "a", "text": "RDI"}, {"id": "b", "text": "RAX"}, {"id": "c", "text": "RCX"}], "correctId": "b", "explanation": "RAX définit toujours l'identifiant (ID) de l'appel système que vous souhaitez réaliser."}},
    {"id": "ex-mod20-2", "type": "quiz", "question": "Où devez-vous placer le code de retour d'un programme pour le syscall 'exit' ?", "difficulty": "easy", "xpReward": 20, "data": {"choices": [{"id": "a", "text": "Dans RDI (Le 1er argument)."}, {"id": "b", "text": "Dans RAX."}, {"id": "c", "text": "Sur la pile."}], "correctId": "a", "explanation": "Comme pour une fonction classique, RDI représente le premier paramètre du syscall (le code d'erreur)."}},
    {"id": "ex-mod20-3", "type": "quiz", "question": "Quelle instruction x86-64 déclenche le passage du User-Space au Kernel-Space sous Linux ?", "difficulty": "medium", "xpReward": 30, "data": {"choices": [{"id": "a", "text": "int 0x80"}, {"id": "b", "text": "syscall"}, {"id": "c", "text": "call kernel"}], "correctId": "b", "explanation": "L'instruction moderne est `syscall`. Historiquement sur 32-bits, on utilisait l'interruption logicielle `int 0x80`."}},
    {"id": "ex-mod20-4", "type": "fill-blank", "question": "Écrire dans le terminal", "difficulty": "medium", "xpReward": 35, "data": {"codeTemplate": "mov rax, 1      ; sys_write\nmov __BLANK__, 1      ; file descriptor (1 = stdout)\nmov rsi, msg    ; buffer\nmov rdx, 13     ; taille\nsyscall", "blanks": [{"id": "1", "answer": "rdi", "hint": "Le registre du 1er argument."}], "explanation": "RDI prend toujours le File Descriptor (0=stdin, 1=stdout, 2=stderr)."}},
    {"id": "ex-mod20-5", "type": "quiz", "question": "Comment le noyau Linux retourne-t-il le résultat ou le statut du syscall (ex: sys_read) ?", "difficulty": "medium", "xpReward": 30, "data": {"choices": [{"id": "a", "text": "Dans RDI."}, {"id": "b", "text": "Dans RAX."}, {"id": "c", "text": "Il n'y a pas de retour."}], "correctId": "b", "explanation": "Le noyau remplace le numéro de syscall dans RAX par la valeur de retour (ex: nombre d'octets lus, ou une erreur négative)."}},
    {"id": "ex-mod20-6", "type": "quiz", "question": "Pourquoi les registres RCX et R11 sont-ils 'détruits' (écrasés) silencieusement après l'instruction `syscall` ?", "difficulty": "hard", "xpReward": 50, "data": {"choices": [{"id": "a", "text": "Le processeur les utilise matériellement pour sauvegarder l'adresse de retour (RIP) et l'état des flags avant de sauter dans le noyau."}, {"id": "b", "text": "C'est un bug de Linux."}, {"id": "c", "text": "Ils servent à transmettre des mots de passe."}], "correctId": "a", "explanation": "L'instruction CPU `syscall` écrase RCX avec l'adresse de retour et R11 avec le RFLAGS, évitant ainsi des accès lents à la pile."}},
    {"id": "ex-mod20-7", "type": "drag-drop", "question": "Les Registres de l'Appel Système", "difficulty": "hard", "xpReward": 50, "data": {"items": [{"id": "1", "text": "RAX (Numéro du Syscall)"}, {"id": "2", "text": "RDI (Arg 1)"}, {"id": "3", "text": "RSI (Arg 2)"}, {"id": "4", "text": "RDX (Arg 3)"}, {"id": "5", "text": "R10 (Arg 4)"}], "correctOrder": ["1", "2", "3", "4", "5"], "instruction": "Ordonnez les registres selon la convention d'Appel Système Linux x86-64.", "explanation": "Attention : contrairement à l'ABI C (qui utilise RCX pour l'arg 4), le Syscall utilise R10 car RCX est détruit !"}},
    {"id": "ex-mod20-8", "type": "fill-blank", "question": "Syscall vDSO (Virtual Dynamically Shared Object)", "difficulty": "hard", "xpReward": 50, "data": {"codeTemplate": "; L'OS mappe une petite zone mémoire partagée dans chaque processus pour éviter certains syscalls lents.\n; Typiquement, la fonction __BLANK__ (heure du système) l'utilise.", "blanks": [{"id": "1", "answer": "gettimeofday", "hint": "Prendre le temps."}], "explanation": "Récupérer l'heure des millions de fois par seconde crasherait le système si on devait faire un Context Switch à chaque fois. Le vDSO permet de lire la mémoire du Kernel directement depuis l'espace utilisateur sans ralentissement."}},
    {"id": "ex-mod20-9", "type": "quiz", "question": "Comment gérez-vous une erreur retournée par un syscall (comme Fichier introuvable sur sys_open) ?", "difficulty": "hard", "xpReward": 50, "data": {"choices": [{"id": "a", "text": "Le noyau lève une exception C++."}, {"id": "b", "text": "Le programme plante avec une SEGFAULT."}, {"id": "c", "text": "RAX contient une valeur négative (entre -1 et -4095) représentant le code d'erreur (errno)."}], "correctId": "c", "explanation": "En Assembleur, il faut toujours vérifier si RAX est strictement inférieur à 0. (ex: `cmp rax, 0` puis `jl erreur`)."}},
    {"id": "ex-mod20-10", "type": "code-correction", "question": "Syscall vs Fonction C", "difficulty": "hard", "xpReward": 50, "data": {"buggyCode": "mov rax, 1\nmov rdi, 1\nmov rsi, msg\nmov rdx, 10\nmov rcx, 0 ; Quatrième argument\nsyscall", "correctCode": "mov rax, 1\nmov rdi, 1\nmov rsi, msg\nmov rdx, 10\nmov r10, 0 ; Quatrième argument pour un SYSCALL\nsyscall", "hints": ["Rappelez-vous la subtile différence d'ABI entre Linux Userspace et Linux Kernelspace."], "explanation": "L'argument n°4 passe dans RCX pour une fonction normale, mais dans R10 pour un Syscall (car RCX est détruit)."}}
])

# --- MODULE 21 : Manipulation de Chaînes ---
exercises.extend([
    {"id": "ex-mod21-1", "type": "quiz", "question": "Quel registre est implicitement utilisé comme compteur de boucle par le préfixe `rep` ?", "difficulty": "easy", "xpReward": 20, "data": {"choices": [{"id": "a", "text": "RAX"}, {"id": "b", "text": "RCX"}, {"id": "c", "text": "RDI"}], "correctId": "b", "explanation": "`rep` décrémente RCX jusqu'à 0 et exécute l'instruction de chaîne à chaque itération."}},
    {"id": "ex-mod21-2", "type": "quiz", "question": "Que fait l'instruction `stosb` ?", "difficulty": "easy", "xpReward": 20, "data": {"choices": [{"id": "a", "text": "Elle écrit le contenu du registre AL à l'adresse pointée par RDI, puis incrémente RDI."}, {"id": "b", "text": "Elle lit la mémoire et la met dans AL."}, {"id": "c", "text": "Elle copie RSI vers RDI."}], "correctId": "a", "explanation": "STore String Byte. C'est le bloc de base du `memset`."}},
    {"id": "ex-mod21-3", "type": "quiz", "question": "Que fait l'instruction `movsb` ?", "difficulty": "medium", "xpReward": 30, "data": {"choices": [{"id": "a", "text": "Elle copie 1 octet de AL vers RDI."}, {"id": "b", "text": "Elle copie 1 octet de l'adresse pointée par RSI vers l'adresse pointée par RDI, puis incrémente les deux registres."}, {"id": "c", "text": "Elle copie RDI vers RSI."}], "correctId": "b", "explanation": "MOVe String Byte. C'est le cœur d'un `memcpy` natif en un seul opcode."}},
    {"id": "ex-mod21-4", "type": "fill-blank", "question": "Direction Flag", "difficulty": "medium", "xpReward": 35, "data": {"codeTemplate": "; Avant d'utiliser rep movsb, je m'assure que le parcours se fait en avançant (de gauche à droite).\n__BLANK__\nrep movsb", "blanks": [{"id": "1", "answer": "cld", "hint": "Clear Direction Flag"}], "explanation": "L'instruction 'cld' (Clear Direction Flag) met le flag DF à 0. L'instruction opposée est 'std' (Set DF) pour parcourir à l'envers."}},
    {"id": "ex-mod21-5", "type": "quiz", "question": "Quelle est la principale utilité du préfixe `repnz scasb` (Scan String Byte) ?", "difficulty": "medium", "xpReward": 30, "data": {"choices": [{"id": "a", "text": "Trouver la longueur d'une chaîne de caractères (strlen) en cherchant le caractère nul (AL=0)."}, {"id": "b", "text": "Copier une chaîne."}, {"id": "c", "text": "Effacer la RAM."}], "correctId": "a", "explanation": "`repnz` s'arrête si RCX devient 0 OU si `scasb` trouve l'octet cherché (Zero Flag passe à 1)."}},
    {"id": "ex-mod21-6", "type": "quiz", "question": "Lors d'un chevauchement de mémoire (Overlap) lors d'une copie, faut-il utiliser `rep movsb` de gauche à droite, ou de droite à gauche ?", "difficulty": "hard", "xpReward": 50, "data": {"choices": [{"id": "a", "text": "Si la destination est plus grande en mémoire, il faut copier de droite à gauche avec 'std' pour ne pas écraser les données non-lues."}, {"id": "b", "text": "Toujours de gauche à droite (cld)."}, {"id": "c", "text": "Peu importe."}], "correctId": "a", "explanation": "C'est l'essence même de la différence entre `memcpy` (qui suppose aucun chevauchement) et `memmove` (qui gère l'Overlap intelligemment)."}},
    {"id": "ex-mod21-7", "type": "drag-drop", "question": "Opération Memset", "difficulty": "hard", "xpReward": 50, "data": {"items": [{"id": "1", "text": "mov al, 0x00 ; Valeur de remplissage"}, {"id": "2", "text": "mov rdi, adresse_buffer ; Destination"}, {"id": "3", "text": "mov rcx, 100 ; Nombre d'octets à remplir"}, {"id": "4", "text": "cld ; Direction en avant"}, {"id": "5", "text": "rep stosb ; Exécution"}], "correctOrder": ["1", "2", "3", "4", "5"], "instruction": "Formez l'algorithme standard pour remplir un buffer de zéros (memset).", "explanation": "C'est l'implémentation la plus propre d'un memset en x86."}},
    {"id": "ex-mod21-8", "type": "fill-blank", "question": "Optimisation des String Operations", "difficulty": "hard", "xpReward": 50, "data": {"codeTemplate": "; Copier octet par octet (stosb) est lent.\n; Copier 8 octets à la fois est bien plus rapide sur un OS 64-bits.\nrep __BLANK__", "blanks": [{"id": "1", "answer": "stosq", "hint": "STore String Quadword."}], "explanation": "Les variantes Q (Quadword - 64 bits), D (Doubleword - 32 bits) et W (Word - 16 bits) permettent d'utiliser le plein potentiel du bus mémoire."}},
    {"id": "ex-mod21-9", "type": "quiz", "question": "Pourquoi les compilateurs modernes C (gcc/clang) n'utilisent-ils presque plus jamais `rep movsb` pour les grosses copies ?", "difficulty": "hard", "xpReward": 50, "data": {"choices": [{"id": "a", "text": "Parce que l'OS l'interdit."}, {"id": "b", "text": "Parce qu'utiliser les registres vectoriels SIMD (AVX, SSE) pour copier 32 ou 64 octets d'un coup est largement plus rapide sur les architectures modernes."}, {"id": "c", "text": "Parce qu'il comporte un bug de sécurité."}], "correctId": "b", "explanation": "Historiquement ultra-rapide, le Microcode interne du CPU pour `rep movsb` a souvent été moins optimisé que l'implémentation agressive d'une boucle AVX."}},
    {"id": "ex-mod21-10", "type": "code-correction", "question": "strlen natif", "difficulty": "hard", "xpReward": 50, "data": {"buggyCode": "mov rdi, chaine\nmov al, 0\nmov rcx, -1\nrep scasb\n; La longueur est maintenant dans RCX ?", "correctCode": "mov rdi, chaine\nmov al, 0\nmov rcx, -1\nrepnz scasb\n; (not rcx) - 1 donnera la longueur", "hints": ["repnz (Repeat Not Zero) et non rep (qui s'arrêterait n'importe quand)."], "explanation": "`repnz scasb` va s'arrêter quand AL == [RDI], c'est à dire au caractère de fin nul '\\0'."}}
])

# --- MODULE 22 : Programmation Concurrente ---
exercises.extend([
    {"id": "ex-mod22-1", "type": "quiz", "question": "Que signifie le fait qu'une instruction soit ATOMIQUE ?", "difficulty": "easy", "xpReward": 20, "data": {"choices": [{"id": "a", "text": "Elle s'exécute de façon indivisible : aucun autre processeur ou thread ne peut l'interrompre ou voir un état intermédiaire."}, {"id": "b", "text": "Elle provoque une explosion nucléaire."}, {"id": "c", "text": "Elle prend très peu de RAM."}], "correctId": "a", "explanation": "Sans atomicité, deux threads modifiant la même variable écraseront l'un l'autre à cause des Context Switches imprévisibles."}},
    {"id": "ex-mod22-2", "type": "quiz", "question": "L'instruction `inc qword [compteur]` (incrémentation en mémoire) est-elle naturellement atomique ?", "difficulty": "easy", "xpReward": 20, "data": {"choices": [{"id": "a", "text": "Oui."}, {"id": "b", "text": "Non, c'est en fait une suite de 3 étapes (Lecture depuis RAM -> Addition dans le CPU -> Écriture en RAM) pouvant être interrompues."}, {"id": "c", "text": "Non, elle ne marche que sur les registres."}], "correctId": "b", "explanation": "C'est la cause numéro 1 des 'Race Conditions'."}},
    {"id": "ex-mod22-3", "type": "quiz", "question": "Quel préfixe x86 faut-il ajouter pour garantir l'atomicité de certaines instructions comme `add` ou `inc` avec la mémoire ?", "difficulty": "medium", "xpReward": 30, "data": {"choices": [{"id": "a", "text": "rep"}, {"id": "b", "text": "lock"}, {"id": "c", "text": "atomic"}], "correctId": "b", "explanation": "Exemple: `lock inc qword [compteur]`. Le CPU verrouille le bus mémoire matériel le temps de l'opération."}},
    {"id": "ex-mod22-4", "type": "fill-blank", "question": "Création d'un Spinlock Mutex", "difficulty": "medium", "xpReward": 35, "data": {"codeTemplate": "acquire_lock:\n  mov eax, 1\n  ; Échange atomiquement EAX et le verrou mémoire\n  __BLANK__ [verrou], eax\n  cmp eax, 0\n  jne acquire_lock ; Si l'ancienne valeur était déjà 1, on boucle", "blanks": [{"id": "1", "answer": "xchg", "hint": "Echange (eXCHanGe)."}], "explanation": "L'instruction `xchg` avec un opérande mémoire est TOUJOURS atomique par défaut en x86, même sans préfixe `lock`."}},
    {"id": "ex-mod22-5", "type": "quiz", "question": "Que signifie CAS (Compare-And-Swap) dans la concurrence Lock-Free ?", "difficulty": "medium", "xpReward": 30, "data": {"choices": [{"id": "a", "text": "C'est un antivirus."}, {"id": "b", "text": "Le CPU compare la RAM à une valeur attendue. Si c'est égal, il écrit la nouvelle valeur, le tout en une seule opération magique atomique."}, {"id": "c", "text": "C'est un appel système Linux."}], "correctId": "b", "explanation": "En x86, CAS est implémenté par la puissante instruction `cmpxchg`."}},
    {"id": "ex-mod22-6", "type": "quiz", "question": "Quel est le problème principal d'un 'Spinlock' (boucle while) pour protéger une ressource ?", "difficulty": "hard", "xpReward": 50, "data": {"choices": [{"id": "a", "text": "Il consomme 100% du CPU pour tourner dans le vide si le verrou est détenu par un autre thread lent."}, {"id": "b", "text": "Il est trop complexe à coder."}, {"id": "c", "text": "Il n'est pas atomique."}], "correctId": "a", "explanation": "C'est pourquoi, en espace utilisateur (Userspace), on préfère appeler l'OS (Mutex/Futex) pour que le thread soit endormi ('Sleep') et réveillé plus tard."}},
    {"id": "ex-mod22-7", "type": "drag-drop", "question": "Le FUTEX de Linux (Fast Userspace Mutex)", "difficulty": "hard", "xpReward": 50, "data": {"items": [{"id": "1", "text": "Le Thread A utilise `lock cmpxchg` pour prendre le verrou en userspace (Ultra rapide, pas d'OS)"}, {"id": "2", "text": "Le Thread B tente un `lock cmpxchg` mais voit que la ressource est verrouillée"}, {"id": "3", "text": "Le Thread B invoque le Syscall `futex` demandant à l'OS de l'endormir (Lent, changement de contexte)"}, {"id": "4", "text": "Le Thread A relâche le verrou (`mov [verrou], 0`) et appelle `futex` pour réveiller B"}], "correctOrder": ["1", "2", "3", "4"], "instruction": "Déroulez l'exécution parfaite d'un Mutex C++ ou POSIX moderne.", "explanation": "Le Futex (Fast Userspace Mutex) marie la vitesse de l'ASM pur (pas de syscall si pas de conflit) et la politesse de l'OS (endormissement au lieu du Spinlock coûteux)."}},
    {"id": "ex-mod22-8", "type": "fill-blank", "question": "La Barrière Mémoire", "difficulty": "hard", "xpReward": 50, "data": {"codeTemplate": "; Empêche le CPU de réordonner (Out-of-Order execution) les écritures mémoire autour de cette instruction.\n__BLANK__", "blanks": [{"id": "1", "answer": "mfence", "hint": "Memory Fence."}], "explanation": "Les CPU modernes modifient l'ordre de vos instructions ASM pour aller plus vite. En multithreading Lock-Free agressif, une barrière `mfence` empêche l'anarchie."}},
    {"id": "ex-mod22-9", "type": "quiz", "question": "L'instruction `pause` à l'intérieur d'un Spinlock sert-elle à endormir le thread ?", "difficulty": "hard", "xpReward": 50, "data": {"choices": [{"id": "a", "text": "Oui, elle appelle le noyau Linux."}, {"id": "b", "text": "Non, elle indique simplement au CPU qu'il est dans un Spin-Loop pour qu'il économise de l'énergie et optimise le pipeline (évite un memory order violation)."}, {"id": "c", "text": "Elle arrête la musique."}], "correctId": "b", "explanation": "Insérer `pause` dans une boucle d'attente active est la meilleure pratique x86."}},
    {"id": "ex-mod22-10", "type": "code-correction", "question": "Implémentation d'un flag Atomics C++11", "difficulty": "hard", "xpReward": 50, "data": {"buggyCode": "add [compteur], 5", "correctCode": "lock add dword [compteur], 5", "hints": ["Faites que ça soit Thread-Safe (Atomique)."], "explanation": "C++ std::atomic<int> produit exactement ceci sous le capot. Un simple `add` sans `lock` amènera à un crash désastreux et difficile à déboguer en production."}}
])

# Write out the file
typescript_content = f"""import {{ Exercise, QuizData, FillBlankData, DragDropData, InteractiveLabData, CodeCorrectionData }} from '../../types';

export const linuxExercises: Exercise[] = {json.dumps(exercises, indent=2)};
"""

# Replace dictionaries in `data` with casted types to strictly follow TS types.
import re

typescript_content = re.sub(r'(\s+)"data": ({{.*?}})', r'\1"data": \2 as any', typescript_content, flags=re.DOTALL)

with open('lib/content/exercises/linux.ts', 'w', encoding='utf-8') as f:
    f.write(typescript_content)

print("Created 50 linux exercises successfully!")
