import json
import re

exercises = []

# --- MODULE 1 : Introduction ---
exercises.extend([
    {"id": "ex-mod1-1", "type": "quiz", "question": "Qu'est-ce que l'Assembleur par rapport au code machine (binaire) ?", "difficulty": "easy", "xpReward": 20, "data": {"choices": [{"id": "a", "text": "Une version textuelle et lisible (Mnémoniques) des instructions binaires brutes (Opcodes) comprises par le processeur."}, {"id": "b", "text": "Un langage de haut niveau comme Python."}, {"id": "c", "text": "Un compilateur C++."}], "correctId": "a", "explanation": "L'Assembleur est simplement une traduction 1 pour 1 du code machine en mots humains."}},
    {"id": "ex-mod1-2", "type": "quiz", "question": "Quelle est la principale différence entre la syntaxe Intel et la syntaxe AT&T ?", "difficulty": "easy", "xpReward": 20, "data": {"choices": [{"id": "a", "text": "Intel utilise l'ordre (Destination, Source), AT&T utilise (Source, Destination) et ajoute des % devant les registres."}, {"id": "b", "text": "Intel est plus lente."}, {"id": "c", "text": "AT&T est pour Windows, Intel pour Linux."}], "correctId": "a", "explanation": "La syntaxe Intel (`mov rax, 5`) est la plus populaire pour l'apprentissage et le reverse engineering."}},
    {"id": "ex-mod1-3", "type": "quiz", "question": "Quel est le nom du programme qui transforme votre fichier texte .asm en un fichier objet binaire (.o) ?", "difficulty": "medium", "xpReward": 30, "data": {"choices": [{"id": "a", "text": "L'Assembleur (ex: NASM, YASM)."}, {"id": "b", "text": "L'Éditeur de Liens (Linker)."}, {"id": "c", "text": "Le Débogueur (GDB)."}], "correctId": "a", "explanation": "Un programme assembleur (comme NASM) lit les mnémoniques et crache des opcodes binaires."}},
    {"id": "ex-mod1-4", "type": "fill-blank", "question": "Structure de base NASM", "difficulty": "medium", "xpReward": 35, "data": {"codeTemplate": "global __BLANK__\n\nsection .text\n__BLANK__:\n  mov rax, 60\n  mov rdi, 0\n  syscall", "blanks": [{"id": "1", "answer": "_start", "hint": "Point d'entrée natif Linux."}, {"id": "2", "answer": "_start", "hint": "Le label de début."}], "explanation": "La fonction `_start` est le véritable point d'entrée natif d'un programme Linux, bien avant que `main` ne soit appelé."}},
    {"id": "ex-mod1-5", "type": "quiz", "question": "À quoi servent les 'Commentaires' et comment les écrit-on en NASM ?", "difficulty": "medium", "xpReward": 30, "data": {"choices": [{"id": "a", "text": "Ils commencent par un point-virgule (;) et sont ignorés par le processeur. Ils sont vitaux en ASM."}, {"id": "b", "text": "Ils commencent par //."}, {"id": "c", "text": "Ils sont exécutés par le CPU."}], "correctId": "a", "explanation": "Le point-virgule (`;`) est la norme pour l'assembleur x86."}},
    {"id": "ex-mod1-6", "type": "quiz", "question": "Qu'est-ce qu'une 'Instruction' (Opcode) ?", "difficulty": "hard", "xpReward": 50, "data": {"choices": [{"id": "a", "text": "Une suite de bits (généralement 1 à 15 octets en x86) qui déclenche un comportement matériel précis gravé dans le silicium du CPU."}, {"id": "b", "text": "Une fonction C++."}, {"id": "c", "text": "Un bloc de mémoire RAM."}], "correctId": "a", "explanation": "Le CPU lit ces bits et ouvre/ferme des transistors (portes logiques) pour effectuer l'action."}},
    {"id": "ex-mod1-7", "type": "drag-drop", "question": "Ordre de compilation Assembleur", "difficulty": "hard", "xpReward": 50, "data": {"items": [{"id": "1", "text": "Écriture du code (main.asm)"}, {"id": "2", "text": "Assemblage: nasm -f elf64 main.asm -o main.o"}, {"id": "3", "text": "Édition de liens: ld main.o -o main"}, {"id": "4", "text": "Exécution: ./main"}], "correctOrder": ["1", "2", "3", "4"], "instruction": "Rangez le processus de la création brute à l'exécution.", "explanation": "NASM crée le fichier Objet (les binaires purs), mais `ld` l'enveloppe dans un format ELF exécutable par Linux."}},
    {"id": "ex-mod1-8", "type": "fill-blank", "question": "Différence d'architectures", "difficulty": "hard", "xpReward": 50, "data": {"codeTemplate": "; Le code binaire compilé pour processeur x86 ne fonctionnera JAMAIS sur un processeur __BLANK__ (ex: un Raspberry Pi ou un Mac M1).\n; Leurs jeux d'instructions (ISA) sont totalement incompatibles.", "blanks": [{"id": "1", "answer": "ARM", "hint": "L'architecture mobile dominante."}], "explanation": "Chaque famille de processeurs (x86, ARM, RISC-V) parle une langue étrangère. Les opcodes de l'un n'ont aucun sens pour l'autre."}},
    {"id": "ex-mod1-9", "type": "quiz", "question": "Pourquoi l'Assembleur x86 est-il qualifié de CISC (Complex Instruction Set Computer) ?", "difficulty": "hard", "xpReward": 50, "data": {"choices": [{"id": "a", "text": "Parce qu'il possède un nombre immense d'instructions (+1500) dont certaines font des actions très complexes et varient de 1 à 15 octets de longueur."}, {"id": "b", "text": "Parce que c'est difficile à apprendre."}, {"id": "c", "text": "Parce qu'il tourne sur Windows."}], "correctId": "a", "explanation": "À l'inverse, ARM est RISC (Reduced Instruction Set Computer) : peu d'instructions, et elles font toutes exactement 4 octets."}},
    {"id": "ex-mod1-10", "type": "code-correction", "question": "Point d'entrée ELF", "difficulty": "hard", "xpReward": 50, "data": {"buggyCode": "global main\n\nsection .data\n\nsection .text\nmain:\n  mov rax, 60\n  mov rdi, 0\n  syscall", "correctCode": "global _start\n\nsection .data\n\nsection .text\n_start:\n  mov rax, 60\n  mov rdi, 0\n  syscall", "hints": ["L'éditeur de liens par défaut (ld) cherche toujours l'étiquette (label) spéciale '_start'."], "explanation": "`main` est une convention du langage C (utilisée si on compile avec `gcc`). En assembleur pur (lié avec `ld`), l'OS cherche `_start`."}}
])

# --- MODULE 2 : Registres & Mémoire ---
exercises.extend([
    {"id": "ex-mod2-1", "type": "quiz", "question": "Combien de bits contient un registre x86-64 commençant par 'R' (ex: RAX, RDI) ?", "difficulty": "easy", "xpReward": 20, "data": {"choices": [{"id": "a", "text": "32 bits"}, {"id": "b", "text": "64 bits"}, {"id": "c", "text": "16 bits"}], "correctId": "b", "explanation": "Le préfixe R (Register) indique 64-bits (8 octets). Le préfixe E (Extended) indique 32-bits (ex: EAX)."}},
    {"id": "ex-mod2-2", "type": "quiz", "question": "Lequel de ces registres est le 'Compteur de Programme' (Program Counter / Instruction Pointer) ?", "difficulty": "easy", "xpReward": 20, "data": {"choices": [{"id": "a", "text": "RIP"}, {"id": "b", "text": "RAX"}, {"id": "c", "text": "RBP"}], "correctId": "a", "explanation": "RIP pointe toujours vers l'adresse mémoire de la prochaine instruction à exécuter."}},
    {"id": "ex-mod2-3", "type": "quiz", "question": "Comment déplacer la valeur 42 dans le registre RAX ?", "difficulty": "medium", "xpReward": 30, "data": {"choices": [{"id": "a", "text": "mov rax, 42"}, {"id": "b", "text": "put 42, rax"}, {"id": "c", "text": "copy rax, 42"}], "correctId": "a", "explanation": "L'instruction MOVe en syntaxe Intel met la source (à droite) dans la destination (à gauche)."}},
    {"id": "ex-mod2-4", "type": "fill-blank", "question": "Sous-Registres", "difficulty": "medium", "xpReward": 35, "data": {"codeTemplate": "; RAX est le registre 64-bits complet.\n; __BLANK__ est la partie basse 32-bits.\n; __BLANK__ est la partie basse 16-bits.\n; AL est la partie très basse 8-bits.", "blanks": [{"id": "1", "answer": "eax", "hint": "Extended Accumulator."}, {"id": "2", "answer": "ax", "hint": "Accumulator."}], "explanation": "Ils se partagent physiquement le même espace matériel. Modifier AL modifie RAX."}},
    {"id": "ex-mod2-5", "type": "quiz", "question": "Que signifient les crochets `[ ]` en syntaxe Intel ?", "difficulty": "medium", "xpReward": 30, "data": {"choices": [{"id": "a", "text": "Ils indiquent un déréférencement (comme l'étoile * en C). Le processeur doit aller lire/écrire à l'adresse mémoire (RAM) indiquée entre les crochets."}, {"id": "b", "text": "Ils créent un tableau de taille dynamique."}, {"id": "c", "text": "C'est de la décoration."}], "correctId": "a", "explanation": "`mov rax, rbx` copie une valeur. `mov rax, [rbx]` va chercher la valeur en RAM à l'adresse RBX."}},
    {"id": "ex-mod2-6", "type": "quiz", "question": "Quelle est l'utilité des directives `byte ptr`, `word ptr`, `dword ptr`, `qword ptr` ?", "difficulty": "hard", "xpReward": 50, "data": {"choices": [{"id": "a", "text": "Elles indiquent au processeur la TAILLE des données à lire/écrire en RAM lorsqu'il y a ambiguïté (ex: `mov byte [rbx], 5`)."}, {"id": "b", "text": "Elles effacent la mémoire."}, {"id": "c", "text": "Elles ne sont utiles qu'en C++."}], "correctId": "a", "explanation": "Si j'écris '5' à une adresse, le CPU ne sait pas si c'est 5 sur 1 octet (byte) ou 5 sur 8 octets (qword). Il faut le préciser."}},
    {"id": "ex-mod2-7", "type": "drag-drop", "question": "Tailles des données", "difficulty": "hard", "xpReward": 50, "data": {"items": [{"id": "1", "text": "BYTE (1 octet / 8 bits)"}, {"id": "2", "text": "WORD (2 octets / 16 bits)"}, {"id": "3", "text": "DWORD (4 octets / 32 bits)"}, {"id": "4", "text": "QWORD (8 octets / 64 bits)"}], "correctOrder": ["1", "2", "3", "4"], "instruction": "Rangez les tailles du plus petit au plus grand.", "explanation": "C'est le vocabulaire essentiel pour manipuler la RAM. QWORD (Quad-Word) est la taille par défaut d'un pointeur 64-bits."}},
    {"id": "ex-mod2-8", "type": "fill-blank", "question": "Scale-Index-Base (Tableaux)", "difficulty": "hard", "xpReward": 50, "data": {"codeTemplate": "; Adressage complexe : [Base + Index * Scale + Offset]\n; Si RBX pointe sur le début d'un tableau d'entiers 32-bits (4 octets)\n; Lisez le 5ème élément (Index = 4) de la boucle dans RAX.\nmov rcx, 4\nmov eax, dword [rbx + __BLANK__ * __BLANK__]", "blanks": [{"id": "1", "answer": "rcx", "hint": "Registre index."}, {"id": "2", "answer": "4", "hint": "Scale (Taille d'un int)."}], "explanation": "L'adressage SIB est conçu matériellement pour rendre les boucles C++ 'arr[i]' ultra rapides."}},
    {"id": "ex-mod2-9", "type": "quiz", "question": "Puis-je copier directement le contenu d'une adresse mémoire vers une autre adresse mémoire ? (`mov [dest], [src]`)", "difficulty": "hard", "xpReward": 50, "data": {"choices": [{"id": "a", "text": "Non, c'est formellement interdit en x86. Il faut d'abord charger dans un registre temporaire."}, {"id": "b", "text": "Oui, c'est l'instruction la plus courante."}, {"id": "c", "text": "Seulement si c'est dans la même section."}], "correctId": "a", "explanation": "L'architecture empêche l'accès double à la RAM en un cycle. Solution: `mov rax, [src]` puis `mov [dest], rax`."}},
    {"id": "ex-mod2-10", "type": "code-correction", "question": "Déplacement Mémoire Interdit", "difficulty": "hard", "xpReward": 50, "data": {"buggyCode": "mov qword [var2], qword [var1]", "correctCode": "mov rax, qword [var1]\nmov qword [var2], rax", "hints": ["Rappelez-vous: mémoire vers mémoire est interdit. Utilisez RAX."], "explanation": "Le CPU x86 exige que l'un des deux opérandes d'un `mov` soit un registre (s'il y a accès mémoire)."}}
])

# --- MODULE 3 : Logique & Arithmétique ---
exercises.extend([
    {"id": "ex-mod3-1", "type": "quiz", "question": "Que fait l'instruction `add rax, 10` ?", "difficulty": "easy", "xpReward": 20, "data": {"choices": [{"id": "a", "text": "Elle ajoute 10 à la valeur de RAX et stocke le résultat dans RAX."}, {"id": "b", "text": "Elle met la valeur 10 dans RAX."}, {"id": "c", "text": "Elle vérifie si RAX est égal à 10."}], "correctId": "a", "explanation": "ADD ajoute la source à la destination (Dest = Dest + Source)."}},
    {"id": "ex-mod3-2", "type": "quiz", "question": "Quelle instruction est la version rapide et spécialisée pour ajouter 1 à un registre (x++) ?", "difficulty": "easy", "xpReward": 20, "data": {"choices": [{"id": "a", "text": "inc"}, {"id": "b", "text": "add 1"}, {"id": "c", "text": "++"}], "correctId": "a", "explanation": "L'instruction `inc rax` est l'abréviation de InCrémenter (+1). L'inverse est `dec` (-1)."}},
    {"id": "ex-mod3-3", "type": "quiz", "question": "Quel résultat donne `xor eax, eax` (un eXclusive OR d'un registre contre lui-même) ?", "difficulty": "medium", "xpReward": 30, "data": {"choices": [{"id": "a", "text": "Le registre est rempli de zéros (0)."}, {"id": "b", "text": "Le registre est rempli de 1."}, {"id": "c", "text": "Le programme plante."}], "correctId": "a", "explanation": "Le XOR donne 1 seulement si les bits sont différents. Puisque le registre est comparé à lui-même, tous les bits sont identiques, ce qui donne zéro. C'est l'idiome x86 pour faire `mov eax, 0` en plus court."}},
    {"id": "ex-mod3-4", "type": "fill-blank", "question": "Bitwise AND", "difficulty": "medium", "xpReward": 35, "data": {"codeTemplate": "; Pour vérifier si un nombre dans RAX est pair ou impair,\n; on peut isoler son dernier bit (le bit 0) avec un ET binaire :\n__BLANK__ rax, 1", "blanks": [{"id": "1", "answer": "and", "hint": "L'opérateur AND."}], "explanation": "`and rax, 1` forcera tous les bits supérieurs à 0, et gardera le dernier bit tel quel. (1 = Impair, 0 = Pair)."}},
    {"id": "ex-mod3-5", "type": "quiz", "question": "Que se passe-t-il si vous tentez d'additionner deux nombres et que le résultat dépasse la capacité de 64 bits (ex: RAX = 0xFFFFF... + 1) ?", "difficulty": "medium", "xpReward": 30, "data": {"choices": [{"id": "a", "text": "Le registre RAX repasse à 0 (Integer Overflow) ET le processeur met le Carry Flag (CF) à 1 pour vous prévenir."}, {"id": "b", "text": "Le programme crashe immédiatement avec une erreur Floating Point."}, {"id": "c", "text": "Le processeur fusionne RAX et RBX pour avoir 128 bits."}], "correctId": "a", "explanation": "Contrairement à certains langages qui crashent ou lèvent une exception, l'ASM 'wrap-around' silencieusement mais lève un drapeau."}},
    {"id": "ex-mod3-6", "type": "quiz", "question": "L'instruction `mul rbx` multiplie RAX par RBX. Où est stocké le résultat (qui pourrait faire 128-bits) ?", "difficulty": "hard", "xpReward": 50, "data": {"choices": [{"id": "a", "text": "La moitié haute va dans RDX, la moitié basse va dans RAX (RDX:RAX)."}, {"id": "b", "text": "Le résultat va uniquement dans RAX, on perd la moitié haute."}, {"id": "c", "text": "Dans RCX."}], "correctId": "a", "explanation": "La multiplication de deux 64-bits donne 128-bits. Le CPU force toujours le duo RDX:RAX."}},
    {"id": "ex-mod3-7", "type": "drag-drop", "question": "Table de Vérité (1 bit)", "difficulty": "hard", "xpReward": 50, "data": {"items": [{"id": "1", "text": "0 AND 0 = 0, 1 AND 1 = 1, 1 AND 0 = 0"}, {"id": "2", "text": "0 OR 0 = 0, 1 OR 1 = 1, 1 OR 0 = 1"}, {"id": "3", "text": "0 XOR 0 = 0, 1 XOR 1 = 0, 1 XOR 0 = 1"}, {"id": "4", "text": "NOT 1 = 0, NOT 0 = 1"}], "correctOrder": ["1", "2", "3", "4"], "instruction": "Lisez de haut en bas les opérateurs logiques (AND, OR, XOR, NOT).", "explanation": "Le XOR (eXclusive OR) est le plus utile en crypto : il agit comme un bouton d'inversion contrôlé."}},
    {"id": "ex-mod3-8", "type": "fill-blank", "question": "Division non-signée", "difficulty": "hard", "xpReward": 50, "data": {"codeTemplate": "; Pour diviser RAX par RBX (div rbx)\n; Il faut TOUJOURS nettoyer le registre RDX avant, sinon Floating Point Exception !\n__BLANK__ rdx, rdx\ndiv rbx", "blanks": [{"id": "1", "answer": "xor", "hint": "L'idiome x86 pour mettre à zéro."}], "explanation": "L'instruction `div` prend l'entier de 128-bits RDX:RAX et le divise. Si RDX n'est pas zéro, c'est comme si vous divisiez un nombre gigantesque, ce qui dépasse la capacité du quotient."}},
    {"id": "ex-mod3-9", "type": "quiz", "question": "À quoi sert l'instruction `shl eax, 2` (Shift Left) ?", "difficulty": "hard", "xpReward": 50, "data": {"choices": [{"id": "a", "text": "Elle décale tous les bits de EAX vers la gauche de 2 positions, ce qui équivaut à une multiplication ultra-rapide par 4 (2^2)."}, {"id": "b", "text": "Elle ajoute 2."}, {"id": "c", "text": "Elle efface EAX."}], "correctId": "a", "explanation": "C'est le moyen le plus rapide de multiplier ou diviser par une puissance de deux."}},
    {"id": "ex-mod3-10", "type": "code-correction", "question": "La Division qui Crash", "difficulty": "hard", "xpReward": 50, "data": {"buggyCode": "; On veut diviser RAX par 5\nmov rax, 20\nmov rbx, 5\ndiv rbx", "correctCode": "mov rax, 20\nmov rbx, 5\nxor rdx, rdx ; NETTOYAGE VITAL !\ndiv rbx", "hints": ["Le CPU va planter si RDX contient des détritus."], "explanation": "Rappelez-vous en tout le temps : `div` utilise RDX. Toujours vider RDX."}}
])

# --- MODULE 4 : Contrôle de flux (Jump) ---
exercises.extend([
    {"id": "ex-mod4-1", "type": "quiz", "question": "Quelle instruction met à jour les Drapeaux d'état (EFLAGS) en soustrayant virtuellement deux valeurs, SANS modifier les registres ?", "difficulty": "easy", "xpReward": 20, "data": {"choices": [{"id": "a", "text": "cmp (Compare)"}, {"id": "b", "text": "test"}, {"id": "c", "text": "sub (Subtract)"}], "correctId": "a", "explanation": "`cmp rax, rbx` fait `rax - rbx` pour mettre à jour les flags (Zero, Sign, etc), mais le résultat de la soustraction est jeté."}},
    {"id": "ex-mod4-2", "type": "quiz", "question": "Après une instruction `cmp rax, rbx`, quelle instruction utiliser pour sauter (Jump) si RAX est ÉGAL à RBX ?", "difficulty": "easy", "xpReward": 20, "data": {"choices": [{"id": "a", "text": "je (Jump if Equal)"}, {"id": "b", "text": "jmp (Jump unconditionnal)"}, {"id": "c", "text": "jne (Jump if Not Equal)"}], "correctId": "a", "explanation": "Le saut conditionnel vérifie l'état du Zero Flag (ZF=1 si la soustraction faisait 0, donc égalité)."}},
    {"id": "ex-mod4-3", "type": "quiz", "question": "Comment faire une boucle infinie pure en Assembleur ?", "difficulty": "medium", "xpReward": 30, "data": {"choices": [{"id": "a", "text": "boucle: jmp boucle"}, {"id": "b", "text": "while(1)"}, {"id": "c", "text": "loop boucle"}], "correctId": "a", "explanation": "Créer un label et utiliser un saut inconditionnel (`jmp`) vers lui-même bloque indéfiniment le processeur (comme un while(true))."}},
    {"id": "ex-mod4-4", "type": "fill-blank", "question": "La Boucle For manuelle", "difficulty": "medium", "xpReward": 35, "data": {"codeTemplate": "mov rcx, 10 ; Compteur à 10\nboucle:\n  ; ... action ...\n  __BLANK__ rcx      ; -1\n  cmp rcx, 0\n  __BLANK__ boucle   ; Saute si Non Égal (Not Equal)", "blanks": [{"id": "1", "answer": "dec", "hint": "Décrémenter."}, {"id": "2", "answer": "jne", "hint": "Jump Not Equal."}], "explanation": "C'est l'implémentation standard d'une boucle : on diminue le compteur et on boucle tant qu'il n'a pas touché 0."}},
    {"id": "ex-mod4-5", "type": "quiz", "question": "Quel est le but de l'instruction `test eax, eax` juste avant un `je` ?", "difficulty": "medium", "xpReward": 30, "data": {"choices": [{"id": "a", "text": "Vérifier si EAX vaut 0. C'est plus petit et plus rapide que 'cmp eax, 0'."}, {"id": "b", "text": "Vérifier si EAX contient une erreur."}, {"id": "c", "text": "Tester la RAM."}], "correctId": "a", "explanation": "`test` fait un AND logique au lieu d'une soustraction. `test eax, eax` met le Zero Flag à 1 uniquement si EAX vaut 0."}},
    {"id": "ex-mod4-6", "type": "quiz", "question": "Différence cruciale : Pourquoi y a-t-il des sauts Signés (jg/jl) et des sauts Non-Signés (ja/jb) ?", "difficulty": "hard", "xpReward": 50, "data": {"choices": [{"id": "a", "text": "Parce qu'au niveau binaire, -1 (0xFFFF...) est virtuellement plus grand que 5 (0x0005) si on l'interprète comme Non-Signé ! L'instruction de saut dit au processeur comment interpréter la comparaison."}, {"id": "b", "text": "C'est juste des synonymes."}, {"id": "c", "text": "ja est pour les sauts longs."}], "correctId": "a", "explanation": "Si j'ai -1 (signé) et 5, -1 est PLUS PETIT (`jl`). Mais si ce sont des non-signés (0xFF... et 0x05), le 1er est PLUS GRAND (`ja`)."}},
    {"id": "ex-mod4-7", "type": "drag-drop", "question": "Associer les Sauts (Jump)", "difficulty": "hard", "xpReward": 50, "data": {"items": [{"id": "1", "text": "je (Égal / Zero Flag = 1)"}, {"id": "2", "text": "jne (Différent / Zero Flag = 0)"}, {"id": "3", "text": "jg (Plus Grand / Signé)"}, {"id": "4", "text": "ja (Plus Grand / Non-Signé)"}], "correctOrder": ["1", "2", "3", "4"], "instruction": "Gardez cet ordre. Le but est de mémoriser les abréviations (Equal, Not Equal, Greater, Above).", "explanation": "Above/Below = Non-Signé. Greater/Less = Signé."}},
    {"id": "ex-mod4-8", "type": "fill-blank", "question": "L'instruction LOOP", "difficulty": "hard", "xpReward": 50, "data": {"codeTemplate": "; Historiquement, l'instruction 'loop' décrémente automatiquement RCX et saute si RCX != 0\nmov __BLANK__, 5\nmon_label:\n  ; ... action\n  __BLANK__ mon_label", "blanks": [{"id": "1", "answer": "rcx", "hint": "Le registre Compteur obligatoire."}, {"id": "2", "answer": "loop", "hint": "L'instruction compacte de boucle."}], "explanation": "Aujourd'hui, les compilateurs évitent 'loop' car la combinaison dec+jne est souvent plus rapide (optimisation micro-code)."}},
    {"id": "ex-mod4-9", "type": "quiz", "question": "Qu'est-ce que les Flags (Drapeaux / EFLAGS) concrètement ?", "difficulty": "hard", "xpReward": 50, "data": {"choices": [{"id": "a", "text": "Un registre spécial (RFLAGS) où chaque bit représente un état (ex: le bit 6 est le Zero Flag, le bit 11 est l'Overflow Flag)."}, {"id": "b", "text": "Des variables globales en RAM."}, {"id": "c", "text": "Un système d'exploitation."}], "correctId": "a", "explanation": "L'ALU modifie ces bits après chaque calcul, et les instructions de saut (ex: 'je') ne font que vérifier si un bit précis est à 1."}},
    {"id": "ex-mod4-10", "type": "code-correction", "question": "Saut Involontaire", "difficulty": "hard", "xpReward": 50, "data": {"buggyCode": "cmp rax, 10\nadd rbx, 5  ; Un calcul s'intercale !\nje rax_est_egal_a_10", "correctCode": "cmp rax, 10\nje rax_est_egal_a_10\nadd rbx, 5", "hints": ["L'instruction ADD modifie aussi les flags !"], "explanation": "Les drapeaux (Flags) sont modifiés par presque toutes les opérations arithmétiques. Il faut faire le saut (je) IMMÉDIATEMENT après la comparaison (cmp)."}}
])

# --- MODULE 5 : La Pile (Stack) & Les Fonctions ---
exercises.extend([
    {"id": "ex-mod5-1", "type": "quiz", "question": "Qu'est-ce que la Pile (Stack) dans un programme ?", "difficulty": "easy", "xpReward": 20, "data": {"choices": [{"id": "a", "text": "Une zone de mémoire (RAM) utilisée pour stocker temporairement des variables locales et gérer les appels de fonctions (Adresses de retour)."}, {"id": "b", "text": "Le disque dur."}, {"id": "c", "text": "Une file d'attente réseau."}], "correctId": "a", "explanation": "C'est l'outil de stockage dynamique numéro 1 en assembleur."}},
    {"id": "ex-mod5-2", "type": "quiz", "question": "Quelle particularité topologique la pile x86 possède-t-elle ?", "difficulty": "easy", "xpReward": 20, "data": {"choices": [{"id": "a", "text": "Elle grandit 'vers le bas' : pousser une valeur dessus diminue l'adresse mémoire (RSP)."}, {"id": "b", "text": "Elle grandit vers le haut."}, {"id": "c", "text": "Elle est infinie."}], "correctId": "a", "explanation": "Historiquement, la pile commençait à la fin de la RAM et le Tas (Heap) au début, grandissant l'un vers l'autre."}},
    {"id": "ex-mod5-3", "type": "quiz", "question": "Que fait l'instruction `push rax` concrètement ?", "difficulty": "medium", "xpReward": 30, "data": {"choices": [{"id": "a", "text": "Elle soustrait 8 à RSP (descend le pointeur), puis écrit la valeur de RAX à la nouvelle adresse pointée par RSP."}, {"id": "b", "text": "Elle ajoute 8 à RSP."}, {"id": "c", "text": "Elle met RAX dans la pile."}], "correctId": "a", "explanation": "RSP (Stack Pointer) doit toujours pointer sur le SOMMET (la donnée la plus récente) de la pile."}},
    {"id": "ex-mod5-4", "type": "fill-blank", "question": "Pop", "difficulty": "medium", "xpReward": 35, "data": {"codeTemplate": "; J'ai sauvé la valeur de rdi sur la pile.\npush rdi\n; ... je modifie rdi pour un calcul\n; Pour récupérer l'ancienne valeur :\n__BLANK__ __BLANK__", "blanks": [{"id": "1", "answer": "pop", "hint": "L'inverse de push."}, {"id": "2", "answer": "rdi", "hint": "La destination."}], "explanation": "`pop rdi` lit la valeur pointée par RSP dans RDI, puis AJOUTE 8 à RSP."}},
    {"id": "ex-mod5-5", "type": "quiz", "question": "Que fait l'instruction `call ma_fonction` ?", "difficulty": "medium", "xpReward": 30, "data": {"choices": [{"id": "a", "text": "Elle pousse (push) l'adresse de l'instruction SUIVANTE (l'adresse de retour RIP) sur la pile, puis saute (jmp) au label ma_fonction."}, {"id": "b", "text": "Elle saute simplement au label."}, {"id": "c", "text": "Elle ferme le programme."}], "correctId": "a", "explanation": "C'est vital : en sauvegardant le pointeur d'instruction (RIP) sur la pile, on sait par où revenir à la fin de la fonction."}},
    {"id": "ex-mod5-6", "type": "quiz", "question": "Comment l'instruction `ret` (Return) conclut-elle la fonction ?", "difficulty": "hard", "xpReward": 50, "data": {"choices": [{"id": "a", "text": "Elle dépile (pop) la valeur au sommet de la pile et l'injecte dans RIP (Instruction Pointer), reprenant ainsi l'exécution là où on l'avait quittée."}, {"id": "b", "text": "Elle retourne RAX."}, {"id": "c", "text": "Elle fait un saut au début."}], "correctId": "a", "explanation": "C'est pourquoi il est MORTEL de modifier RSP ou de laisser des 'push' sans 'pop' dans une fonction. `ret` dépilera la mauvaise valeur et sautera dans le néant (Segfault)."}},
    {"id": "ex-mod5-7", "type": "drag-drop", "question": "Le Prologue de Fonction Standard", "difficulty": "hard", "xpReward": 50, "data": {"items": [{"id": "1", "text": "push rbp (Sauvegarder l'ancien Base Pointer de l'appelant)"}, {"id": "2", "text": "mov rbp, rsp (Figer le Base Pointer actuel de notre nouvelle Frame)"}, {"id": "3", "text": "sub rsp, 32 (Allouer de l'espace sur la pile pour nos variables locales)"}, {"id": "4", "text": "mov [rbp - 8], rdi (Sauvegarder les paramètres dans notre Frame)"}], "correctOrder": ["1", "2", "3", "4"], "instruction": "Recréez l'ouverture classique (Prologue) de 99% des fonctions C compilées.", "explanation": "RBP sert d'ancre. Toutes les variables locales seront accédées via `[rbp - N]`."}},
    {"id": "ex-mod5-8", "type": "fill-blank", "question": "L'Épilogue", "difficulty": "hard", "xpReward": 50, "data": {"codeTemplate": "; À la fin de la fonction, on doit détruire notre Stack Frame pour revenir proprement.\n; Étape 1: Restaurer RSP à la base de la frame (supprime les variables locales)\nmov rsp, __BLANK__\n; Étape 2: Restaurer l'ancien Base Pointer\n__BLANK__ rbp\nret", "blanks": [{"id": "1", "answer": "rbp", "hint": "L'ancre."}, {"id": "2", "answer": "pop", "hint": "Dépiler l'ancien RBP."}], "explanation": "L'instruction `leave` fait exactement ces deux opérations (mov rsp, rbp ; pop rbp) en une seule fois."}},
    {"id": "ex-mod5-9", "type": "quiz", "question": "Quel est le risque de la Récursion Infinie en Assembleur ?", "difficulty": "hard", "xpReward": 50, "data": {"choices": [{"id": "a", "text": "Un Stack Overflow (Débordement de pile) : la pile grandit (vers le bas) à chaque 'call' jusqu'à heurter la fin de la RAM autorisée, et crashe."}, {"id": "b", "text": "Le CPU surchauffe."}, {"id": "c", "text": "Aucun risque."}], "correctId": "a", "explanation": "C'est l'origine du nom du fameux site StackOverflow. Chaque appel ajoute au moins 8 octets (l'adresse de retour)."}},
    {"id": "ex-mod5-10", "type": "code-correction", "question": "Le Ret Mortel", "difficulty": "hard", "xpReward": 50, "data": {"buggyCode": "ma_fonction:\n  push rax\n  push rbx\n  ; ... calculs ...\n  pop rbx\n  ret", "correctCode": "ma_fonction:\n  push rax\n  push rbx\n  ; ... calculs ...\n  pop rbx\n  pop rax ; OUBLI MORTEL CORRIGÉ\n  ret", "hints": ["Pour chaque push, il FAUT un pop avant le ret."], "explanation": "Sans le `pop rax`, le sommet de la pile est occupé par la valeur de RAX, et non par l'adresse de retour. `ret` va donc lire la valeur de RAX et sauter bêtement à cette adresse !"}}
])

# Write out the file
typescript_content = f"""import {{ Exercise, QuizData, FillBlankData, DragDropData, InteractiveLabData, CodeCorrectionData }} from '../../types';

export const basicsExercises: Exercise[] = {json.dumps(exercises, indent=2)};
"""

# Type casting
typescript_content = re.sub(r'(\s+)"data": ({{.*?}})', r'\1"data": \2 as any', typescript_content, flags=re.DOTALL)

with open('lib/content/exercises/basics.ts', 'w', encoding='utf-8') as f:
    f.write(typescript_content)

print("Created 50 basics exercises successfully!")
