import json

exercises = []

# --- MODULE 23 ---
exercises.extend([
    {"id": "ex-mod23-1", "type": "quiz", "question": "Combien d'octets prend un int standard en C++ (sur 32/64 bits) par rapport à un entier Python ?", "difficulty": "easy", "xpReward": 20, "data": {"choices": [{"id": "a", "text": "4 octets en C++ contre ~28 octets en Python"}, {"id": "b", "text": "8 octets pour les deux"}, {"id": "c", "text": "Python ne prend pas de RAM"}], "correctId": "a", "explanation": "Un int C++ est brut. Un int Python est un objet (PyLongObject)."}},
    {"id": "ex-mod23-2", "type": "quiz", "question": "Les entiers en Python sont immuables. Qu'est-ce que cela signifie ?", "difficulty": "easy", "xpReward": 20, "data": {"choices": [{"id": "a", "text": "On ne peut pas les additionner."}, {"id": "b", "text": "Chaque modification crée un nouvel objet en mémoire."}, {"id": "c", "text": "Ils ne peuvent pas être négatifs."}], "correctId": "b", "explanation": "Python alloue un nouveau PyObject à chaque calcul, ce qui sollicite le tas (Heap)."}},
    {"id": "ex-mod23-3", "type": "quiz", "question": "Qu'est-ce que le 'Garbage Collector' (GC) fait concrètement en Python ?", "difficulty": "medium", "xpReward": 30, "data": {"choices": [{"id": "a", "text": "Il nettoie le cache du CPU."}, {"id": "b", "text": "Il détruit les objets du Tas dont le 'Reference Count' tombe à zéro."}, {"id": "c", "text": "Il compile le code."}], "correctId": "b", "explanation": "Le GC de Python (CPython) fonctionne principalement par comptage de références."}},
    {"id": "ex-mod23-4", "type": "fill-blank", "question": "L'en-tête d'un objet Python", "difficulty": "medium", "xpReward": 35, "data": {"codeTemplate": "struct PyObject {\n  Py_ssize_t __BLANK__; // Compteur\n  struct _typeobject *__BLANK__; // Pointeur type\n};", "blanks": [{"id": "1", "answer": "ob_refcnt", "hint": "Reference Count."}, {"id": "2", "answer": "ob_type", "hint": "Type."}], "explanation": "C'est l'en-tête de tout objet Python (16 octets)."}},
    {"id": "ex-mod23-5", "type": "quiz", "question": "Dans un std::vector C++, où se trouvent les éléments ?", "difficulty": "medium", "xpReward": 30, "data": {"choices": [{"id": "a", "text": "Répartis aléatoirement."}, {"id": "b", "text": "Dans un bloc de mémoire contigu sur le Tas."}, {"id": "c", "text": "Dans le cache L3 uniquement."}], "correctId": "b", "explanation": "La contiguïté est ce qui rend le vector si rapide."}},
    {"id": "ex-mod23-6", "type": "quiz", "question": "Pourquoi la contiguïté mémoire empêche-t-elle le 'Cache Miss' ?", "difficulty": "hard", "xpReward": 50, "data": {"choices": [{"id": "a", "text": "Parce que le CPU charge la mémoire par 'lignes de cache' (ex: 64 octets d'un coup)."}, {"id": "b", "text": "Parce que le CPU désactive le cache."}, {"id": "c", "text": "Parce que la RAM tourne plus vite."}], "correctId": "a", "explanation": "Charger un élément charge aussi les suivants dans le L1."}},
    {"id": "ex-mod23-7", "type": "drag-drop", "question": "Ordonnez ces accès mémoire du plus rapide au plus lent.", "difficulty": "hard", "xpReward": 50, "data": {"items": [{"id": "1", "text": "Registre (RAX)"}, {"id": "2", "text": "Cache L1"}, {"id": "3", "text": "RAM (Tas)"}, {"id": "4", "text": "SSD (Swap)"}], "correctOrder": ["1", "2", "3", "4"], "instruction": "Placez le composant le plus rapide en haut.", "explanation": "Les registres prennent 1 cycle, le L1 ~4 cycles, la RAM ~300 cycles."}},
    {"id": "ex-mod23-8", "type": "fill-blank", "question": "Accès Scale-Index-Base (SIB)", "difficulty": "hard", "xpReward": 50, "data": {"codeTemplate": "mov eax, [rbx + __BLANK__ * __BLANK__]", "blanks": [{"id": "1", "answer": "rcx", "hint": "Index."}, {"id": "2", "answer": "4", "hint": "Taille d'un entier."}], "explanation": "Le SIB permet de calculer l'adresse en hardware."}},
    {"id": "ex-mod23-9", "type": "quiz", "question": "Pourquoi une liste Python est-elle un tableau de pointeurs et non de valeurs ?", "difficulty": "hard", "xpReward": 50, "data": {"choices": [{"id": "a", "text": "Pour économiser de la RAM."}, {"id": "b", "text": "Pour permettre de stocker des types différents."}, {"id": "c", "text": "Pour éviter les pointeurs."}], "correctId": "b", "explanation": "La liste ne stocke que des adresses (8 octets chacune), causant un double déréférencement."}},
    {"id": "ex-mod23-10", "type": "code-correction", "question": "Corrigez l'erreur de pointeur C++", "difficulty": "hard", "xpReward": 50, "data": {"buggyCode": "int* ptr = &valeur;\nint res = ptr;", "correctCode": "int* ptr = &valeur;\nint res = *ptr;", "hints": ["Il faut déréférencer le pointeur."], "explanation": "L'étoile (*) indique qu'on veut la valeur pointée (comme des crochets [] en ASM)."}}
])

# --- MODULE 24 ---
exercises.extend([
    {"id": "ex-mod24-1", "type": "quiz", "question": "Que signifie le 'Dynamic Dispatch' ?", "difficulty": "easy", "xpReward": 20, "data": {"choices": [{"id": "a", "text": "L'appel de fonction est décidé à l'exécution (runtime)."}, {"id": "b", "text": "Le compilateur supprime la fonction."}, {"id": "c", "text": "L'appel est résolu à la compilation."}], "correctId": "a", "explanation": "En Python, on ne sait pas quelle méthode __eq__ appeler avant de vérifier le type."}},
    {"id": "ex-mod24-2", "type": "quiz", "question": "Comment le compilateur C++ traduit-il une simple condition (a == b) ?", "difficulty": "easy", "xpReward": 20, "data": {"choices": [{"id": "a", "text": "En cherchant une méthode __eq__."}, {"id": "b", "text": "Par une instruction 'cmp' suivie d'un saut ('je')."}, {"id": "c", "text": "Il délègue ça à l'OS."}], "correctId": "b", "explanation": "C++ produit le code machine le plus direct."}},
    {"id": "ex-mod24-3", "type": "quiz", "question": "Qu'est-ce qu'une Frame (Cadre de pile) ?", "difficulty": "medium", "xpReward": 30, "data": {"choices": [{"id": "a", "text": "Une image vidéo."}, {"id": "b", "text": "Une zone sur la pile contenant les variables locales et l'adresse de retour."}, {"id": "c", "text": "Un bloc sur le tas."}], "correctId": "b", "explanation": "À chaque appel, une Stack Frame est créée."}},
    {"id": "ex-mod24-4", "type": "fill-blank", "question": "Dynamic Dispatch", "difficulty": "medium", "xpReward": 35, "data": {"codeTemplate": "call PyObject_RichCompare\n; Python va chercher la fonction __BLANK__", "blanks": [{"id": "1", "answer": "__eq__", "hint": "Méthode d'égalité."}], "explanation": "Là où C++ fait un 'cmp', Python fait une recherche complexe."}},
    {"id": "ex-mod24-5", "type": "quiz", "question": "Comment fonctionnent les Générateurs (yield) ?", "difficulty": "medium", "xpReward": 30, "data": {"choices": [{"id": "a", "text": "Ils sauvegardent l'état (Stack Frame) sur le Tas pour y revenir."}, {"id": "b", "text": "Ils bloquent le CPU."}, {"id": "c", "text": "Ils compilent en temps réel."}], "correctId": "a", "explanation": "Au lieu de détruire la frame, elle est suspendue."}},
    {"id": "ex-mod24-6", "type": "quiz", "question": "En C++20, comment les Coroutines (co_yield) gèrent-elles leur pile ?", "difficulty": "hard", "xpReward": 50, "data": {"choices": [{"id": "a", "text": "C++ utilise une 'Stackless Coroutine', allouant l'état sur le tas."}, {"id": "b", "text": "Elles utilisent des Threads de l'OS."}, {"id": "c", "text": "Elles copient la RAM."}], "correctId": "a", "explanation": "Pour ne pas bloquer de Threads, C++ alloue juste ce qu'il faut."}},
    {"id": "ex-mod24-7", "type": "fill-blank", "question": "L'inlining", "difficulty": "hard", "xpReward": 50, "data": {"codeTemplate": "; Au lieu d'un appel coûteux :\n; Le compilateur fait du __BLANK__ en copiant les instructions.", "blanks": [{"id": "1", "answer": "inlining", "hint": "Intégration."}], "explanation": "L'inlining évite la création de Stack Frame."}},
    {"id": "ex-mod24-8", "type": "drag-drop", "question": "Ordre de résolution d'une méthode virtuelle en C++.", "difficulty": "hard", "xpReward": 50, "data": {"items": [{"id": "1", "text": "Lire le pointeur vptr"}, {"id": "2", "text": "Lire l'adresse dans la VTable"}, {"id": "3", "text": "Sauter (call) à cette adresse"}], "correctOrder": ["1", "2", "3"], "instruction": "Mettez les étapes de la résolution de la VTable dans le bon ordre.", "explanation": "Ce double déréférencement prend ~3 cycles."}},
    {"id": "ex-mod24-9", "type": "quiz", "question": "Pourquoi le Branch Predictor aime le C++ plus que Python ?", "difficulty": "hard", "xpReward": 50, "data": {"choices": [{"id": "a", "text": "Parce que Python utilise des sauts indirects massifs (switch géant) difficiles à deviner."}, {"id": "b", "text": "Parce que C++ est écrit en anglais."}, {"id": "c", "text": "Parce que Python ne saute pas."}], "correctId": "a", "explanation": "L'interpréteur Python vide souvent le pipeline du CPU à cause de mauvaises prédictions."}},
    {"id": "ex-mod24-10", "type": "code-correction", "question": "Appel indirect", "difficulty": "hard", "xpReward": 50, "data": {"buggyCode": "mov rax, [vtable_ptr]\njmp [rax]", "correctCode": "mov rax, [vtable_ptr]\ncall [rax]", "hints": ["On veut pouvoir revenir de la méthode !"], "explanation": "Une méthode virtuelle nécessite un 'call'."}}
])

# --- MODULE 25 ---
exercises.extend([
    {"id": "ex-mod25-1", "type": "quiz", "question": "Qu'est-ce qu'un Context Switch (changement de contexte) ?", "difficulty": "easy", "xpReward": 20, "data": {"choices": [{"id": "a", "text": "Le passage du User-Space au Kernel-Space pour exécuter un syscall."}, {"id": "b", "text": "Changer de variable en C++."}, {"id": "c", "text": "Appuyer sur Alt+Tab."}], "correctId": "a", "explanation": "Le CPU doit sauvegarder tous ses registres et changer ses droits d'accès. C'est très lent (milliers de cycles)."}},
    {"id": "ex-mod25-2", "type": "quiz", "question": "Quelle classe C++ standard permet de lire un fichier de façon bufferisée ?", "difficulty": "easy", "xpReward": 20, "data": {"choices": [{"id": "a", "text": "std::ifstream"}, {"id": "b", "text": "syscall_read"}, {"id": "c", "text": "sys_open"}], "correctId": "a", "explanation": "Les flux iostream (comme ifstream) utilisent un buffer mémoire interne pour limiter les appels système."}},
    {"id": "ex-mod25-3", "type": "quiz", "question": "Pourquoi print() en Python n'appelle-t-il pas l'OS pour chaque caractère 'H', 'e', 'l', 'l', 'o' ?", "difficulty": "medium", "xpReward": 30, "data": {"choices": [{"id": "a", "text": "Il n'en a pas le droit."}, {"id": "b", "text": "Il écrit dans un Buffer en RAM, puis fait un seul gros syscall (sys_write) quand il est plein ou à la fin."}, {"id": "c", "text": "Il l'affiche par magie."}], "correctId": "b", "explanation": "Le buffering est la clé des performances I/O."}},
    {"id": "ex-mod25-4", "type": "fill-blank", "question": "Syscall Write", "difficulty": "medium", "xpReward": 35, "data": {"codeTemplate": "mov rax, 1 ; syscall write\nmov rdi, 1 ; stdout\nmov rsi, adresse_buffer\nmov rdx, __BLANK__ ; taille\n__BLANK__", "blanks": [{"id": "1", "answer": "100", "hint": "Par exemple, écrire 100 octets."}, {"id": "2", "answer": "syscall", "hint": "Interrompre l'exécution pour passer au noyau."}], "explanation": "L'appel système attend la taille du buffer dans RDX."}},
    {"id": "ex-mod25-5", "type": "quiz", "question": "Que signifie RAII en C++ ?", "difficulty": "medium", "xpReward": 30, "data": {"choices": [{"id": "a", "text": "Resource Acquisition Is Initialization."}, {"id": "b", "text": "Random Access Internal Interface."}, {"id": "c", "text": "Read And Ignore Input."}], "correctId": "a", "explanation": "C'est le paradigme où l'obtention d'une ressource (fichier, mémoire) se fait dans le constructeur, et la libération dans le destructeur de façon garantie."}},
    {"id": "ex-mod25-6", "type": "quiz", "question": "Comment le mot-clé 'with' de Python gère-t-il les fichiers sous le capot ?", "difficulty": "hard", "xpReward": 50, "data": {"choices": [{"id": "a", "text": "Il enveloppe le code dans un bloc try...finally et appelle __exit__ pour fermer le fichier même si une exception survient."}, {"id": "b", "text": "Il appelle un syscall spécial 'with'."}, {"id": "c", "text": "Il utilise le RAII du C++."}], "correctId": "a", "explanation": "C'est l'équivalent Python (Context Manager) du destructeur C++ (RAII)."}},
    {"id": "ex-mod25-7", "type": "drag-drop", "question": "Cycle de vie RAII (Fichier)", "difficulty": "hard", "xpReward": 50, "data": {"items": [{"id": "1", "text": "Appel de sys_open (Constructeur)"}, {"id": "2", "text": "Opérations de Lecture (Bufferisées)"}, {"id": "3", "text": "Fin du bloc (Scope) atteinte"}, {"id": "4", "text": "Appel automatique de sys_close (Destructeur)"}], "correctOrder": ["1", "2", "3", "4"], "instruction": "Classez les étapes de la vie d'un std::ifstream.", "explanation": "Le destructeur est inséré de force par le compilateur avant chaque instruction 'ret'."}},
    {"id": "ex-mod25-8", "type": "fill-blank", "question": "O_DIRECT", "difficulty": "hard", "xpReward": 50, "data": {"codeTemplate": "; Pour écrire sur le disque sans passer par le Page Cache de Linux :\nopen(\"fichier.txt\", O_WRONLY | __BLANK__);", "blanks": [{"id": "1", "answer": "O_DIRECT", "hint": "Direct I/O."}], "explanation": "Utilisé par les bases de données (PostgreSQL, MySQL) pour gérer elles-mêmes leur cache RAM sans interférence de l'OS."}},
    {"id": "ex-mod25-9", "type": "quiz", "question": "Pourquoi la libération mémoire (delete/free) n'est-elle généralement pas un simple 'sys_brk' ?", "difficulty": "hard", "xpReward": 50, "data": {"choices": [{"id": "a", "text": "Parce que l'allocateur (malloc/new) préfère recycler les blocs de RAM libres au lieu de les rendre au noyau OS à chaque fois."}, {"id": "b", "text": "Parce qu'on ne peut pas rendre de mémoire à l'OS."}, {"id": "c", "text": "Parce que sys_brk n'existe pas."}], "correctId": "a", "explanation": "Faire un syscall est coûteux. Le malloc de la libc maintient des 'free lists' internes."}},
    {"id": "ex-mod25-10", "type": "code-correction", "question": "Fuite de mémoire", "difficulty": "hard", "xpReward": 50, "data": {"buggyCode": "void faire() {\n  int* data = new int[100];\n  if (erreur) return;\n  delete[] data;\n}", "correctCode": "void faire() {\n  int* data = new int[100];\n  if (erreur) { delete[] data; return; }\n  delete[] data;\n}", "hints": ["Si 'erreur' est vraie, on quitte avant le delete."], "explanation": "C'est pourquoi on utilise std::unique_ptr ou le RAII pour éviter ce genre de fuites garanties."}}
])

# --- MODULE 26 ---
exercises.extend([
    {"id": "ex-mod26-1", "type": "quiz", "question": "Que signifie 'Zéro-overhead' pour les exceptions C++ ?", "difficulty": "easy", "xpReward": 20, "data": {"choices": [{"id": "a", "text": "Si aucune exception n'est lancée (pas de throw), le code s'exécute exactement aussi vite que s'il n'y avait pas de try/catch."}, {"id": "b", "text": "Le throw s'exécute en 0 cycle CPU."}, {"id": "c", "text": "Le code prend 0 octet en mémoire."}], "correctId": "a", "explanation": "C'est la philosophie C++ : vous ne payez pas de pénalité de performance (vitesse) pour une exception qui n'arrive pas."}},
    {"id": "ex-mod26-2", "type": "quiz", "question": "Comment Python gère-t-il les erreurs en interne ?", "difficulty": "easy", "xpReward": 20, "data": {"choices": [{"id": "a", "text": "Avec des Zero-overhead exceptions."}, {"id": "b", "text": "En retournant des pointeurs NULL et en fixant des variables globales d'erreur (PyErr_SetString)."}, {"id": "c", "text": "Il n'y a pas d'erreur en Python."}], "correctId": "b", "explanation": "Le code C sous-jacent de Python vérifie laborieusement si le retour est NULL à chaque ligne."}},
    {"id": "ex-mod26-3", "type": "quiz", "question": "Qu'est-ce que le 'Stack Unwinding' ?", "difficulty": "medium", "xpReward": 30, "data": {"choices": [{"id": "a", "text": "Une instruction CPU."}, {"id": "b", "text": "Le processus par lequel l'OS remonte la pile des appels pour trouver un bloc 'catch' valide lorsqu'un throw se produit."}, {"id": "c", "text": "Une optimisation de boucle."}], "correctId": "b", "explanation": "Le déroulage de pile permet d'appeler les destructeurs locaux de chaque Frame détruite."}},
    {"id": "ex-mod26-4", "type": "fill-blank", "question": "Tables DWARF", "difficulty": "medium", "xpReward": 35, "data": {"codeTemplate": "; Le compilateur génère une section ELF invisible nommée __BLANK__\n; Elle contient la carte des blocs try/catch.", "blanks": [{"id": "1", "answer": ".eh_frame", "hint": "Exception Handling Frame."}], "explanation": "C'est grâce à cette table (sans instructions) que le zero-overhead est possible."}},
    {"id": "ex-mod26-5", "type": "quiz", "question": "Que se passe-t-il si un throw n'est jamais attrapé par un catch en C++ ?", "difficulty": "medium", "xpReward": 30, "data": {"choices": [{"id": "a", "text": "Le programme continue."}, {"id": "b", "text": "L'OS redémarre."}, {"id": "c", "text": "Le programme crashe (appel à std::terminate)."}], "correctId": "c", "explanation": "std::terminate() est appelé, ce qui fait crasher le programme brutalement (abort)."}},
    {"id": "ex-mod26-6", "type": "quiz", "question": "Pourquoi les développeurs de jeux vidéo (moteurs C++) désactivent-ils souvent les exceptions (-fno-exceptions) ?", "difficulty": "hard", "xpReward": 50, "data": {"choices": [{"id": "a", "text": "Parce que le 'Stack Unwinding' cause des pics de lenteur aléatoires inacceptables (des millisecondes perdues)."}, {"id": "b", "text": "Pour avoir plus de couleurs."}, {"id": "c", "text": "Parce qu'ils codent parfaitement."}], "correctId": "a", "explanation": "Dans un jeu à 60 FPS, une frame dure 16ms. Un seul Stack Unwinding peut prendre plusieurs millisecondes et créer un 'stutter' (saccade)."}},
    {"id": "ex-mod26-7", "type": "drag-drop", "question": "Le processus d'un 'throw' C++", "difficulty": "hard", "xpReward": 50, "data": {"items": [{"id": "1", "text": "throw est appelé, arrêt du flux d'exécution normal"}, {"id": "2", "text": "libunwind lit la section .eh_frame pour analyser la pile"}, {"id": "3", "text": "Exécution des destructeurs (RAII) des variables locales (Stack Unwinding)"}, {"id": "4", "text": "Saut dans le bloc 'catch' correspondant"}], "correctOrder": ["1", "2", "3", "4"], "instruction": "Ordonnez les étapes lentes du déclenchement d'une exception.", "explanation": "Ce processus magique mais lourd justifie l'adage 'N'utilisez les exceptions que pour des cas exceptionnels'."}},
    {"id": "ex-mod26-8", "type": "fill-blank", "question": "Vérification d'erreur CPython", "difficulty": "hard", "xpReward": 50, "data": {"codeTemplate": "PyObject *result = PyObject_Call(func, args);\nif (result == __BLANK__) {\n    return __BLANK__; // Propagation manuelle de l'erreur\n}", "blanks": [{"id": "1", "answer": "NULL", "hint": "Pointeur vide."}, {"id": "2", "answer": "NULL", "hint": "Pointeur vide."}], "explanation": "Sous la syntaxe élégante 'try...except' de Python, l'interpréteur C fait des if(result == NULL) des millions de fois par seconde."}},
    {"id": "ex-mod26-9", "type": "quiz", "question": "Comment fonctionnent les alternatives modernes comme Result<T, E> (Rust, std::expected en C++23) ?", "difficulty": "hard", "xpReward": 50, "data": {"choices": [{"id": "a", "text": "Une structure contenant soit la valeur de succès, soit l'erreur, vérifiée explicitement sans Stack Unwinding."}, {"id": "b", "text": "Ils appellent abort() tout le temps."}, {"id": "c", "text": "Ils utilisent la table DWARF."}], "correctId": "a", "explanation": "C'est un retour aux codes d'erreur mais de façon sûre (Memory Safe), évitant la lenteur des exceptions."}},
    {"id": "ex-mod26-10", "type": "code-correction", "question": "Destruction manuelle", "difficulty": "hard", "xpReward": 50, "data": {"buggyCode": "FILE* f = fopen(\"x\", \"r\");\nthrow std::runtime_error(\"Oups\");\nfclose(f);", "correctCode": "FILE* f = fopen(\"x\", \"r\");\n/* Mieux: std::ifstream ou RAII */\nfclose(f);\nthrow std::runtime_error(\"Oups\");", "hints": ["Le throw quitte immédiatement la fonction."], "explanation": "Le fclose ne sera jamais exécuté. RAII résout cela car le destructeur est appelé automatiquement pendant le Stack Unwinding."}}
])

# --- MODULE 27 ---
exercises.extend([
    {"id": "ex-mod27-1", "type": "quiz", "question": "Qu'est-ce que le 'Duck Typing' en Python ?", "difficulty": "easy", "xpReward": 20, "data": {"choices": [{"id": "a", "text": "Si ça marche comme un canard et cancane comme un canard, c'est un canard (on vérifie la présence des méthodes à l'exécution, peu importe le type réel)."}, {"id": "b", "text": "Une erreur de typage."}, {"id": "c", "text": "Une optimisation."}], "correctId": "a", "explanation": "Pas besoin d'interfaces héritées stricte en Python, tant que l'objet possède la méthode requise."}},
    {"id": "ex-mod27-2", "type": "quiz", "question": "Qu'est-ce que la VTable en C++ ?", "difficulty": "easy", "xpReward": 20, "data": {"choices": [{"id": "a", "text": "Une table en bois."}, {"id": "b", "text": "Un tableau statique de pointeurs de fonctions pour résoudre le polymorphisme (Virtual Methods)."}, {"id": "c", "text": "Une liste Python."}], "correctId": "b", "explanation": "La Virtual Method Table permet les appels indirects."}},
    {"id": "ex-mod27-3", "type": "quiz", "question": "Où est stocké le 'vptr' (Virtual Pointer) d'un objet C++ ?", "difficulty": "medium", "xpReward": 30, "data": {"choices": [{"id": "a", "text": "En tant que champ caché à l'intérieur (généralement au tout début) de chaque instance de l'objet en RAM."}, {"id": "b", "text": "Dans le fichier texte."}, {"id": "c", "text": "Dans la VTable elle-même."}], "correctId": "a", "explanation": "Si une classe a des méthodes virtuelles, le compilateur grossit chaque instance de 8 octets (64-bits) pour y cacher le vptr."}},
    {"id": "ex-mod27-4", "type": "fill-blank", "question": "Appel d'une méthode virtuelle", "difficulty": "medium", "xpReward": 35, "data": {"codeTemplate": "mov rax, [rbx] ; 1. Lire le vptr (situé au début de l'objet dans rbx)\ncall [rax + __BLANK__] ; 2. Appeler la 2ème méthode virtuelle", "blanks": [{"id": "1", "answer": "8", "hint": "Offset de 8 octets pour la 2ème fonction (pointers de 64-bits)."}], "explanation": "L'offset est fixé à la compilation (0 pour la 1ère méthode, 8 pour la 2ème, 16 pour la 3ème...)."}},
    {"id": "ex-mod27-5", "type": "quiz", "question": "Qu'est-ce qu'une Closure (Fermeture) / Fonction Lambda ?", "difficulty": "medium", "xpReward": 30, "data": {"choices": [{"id": "a", "text": "Une fonction qui encapsule ('capture') des variables de son environnement englobant pour les utiliser plus tard."}, {"id": "b", "text": "Une fonction qui ferme le programme."}, {"id": "c", "text": "Un type de VTable."}], "correctId": "a", "explanation": "Elle permet à une fonction de survivre avec un état mémoire interne caché."}},
    {"id": "ex-mod27-6", "type": "quiz", "question": "Comment le compilateur C++ transforme-t-il une Lambda avec capture `[x](int y) { return x + y; }` ?", "difficulty": "hard", "xpReward": 50, "data": {"choices": [{"id": "a", "text": "En créant secrètement une classe (struct) dont les membres sont les variables capturées, et surchargeant l'opérateur operator()."}, {"id": "b", "text": "En copiant x dans un registre éternel."}, {"id": "c", "text": "En bloquant le multithreading."}], "correctId": "a", "explanation": "Une fonction lambda n'est qu'un sucre syntaxique pour créer une classe/foncteur anonyme."}},
    {"id": "ex-mod27-7", "type": "drag-drop", "question": "Coût de résolution de méthode", "difficulty": "hard", "xpReward": 50, "data": {"items": [{"id": "1", "text": "Appel direct (C++ normal, call adr)"}, {"id": "2", "text": "Appel virtuel (C++ vptr, call [rax+8])"}, {"id": "3", "text": "Duck Typing (Python __dict__ hash map search)"}], "correctOrder": ["1", "2", "3"], "instruction": "Classez du plus rapide (1 cycle) au plus lent (100+ cycles).", "explanation": "L'appel direct est immédiat, le VTable ajoute des accès mémoire, le Duck Typing fait appel à des milliers d'instructions internes."}},
    {"id": "ex-mod27-8", "type": "fill-blank", "question": "Dictionnaire Python", "difficulty": "hard", "xpReward": 50, "data": {"codeTemplate": "PyObject* __BLANK__ = obj->ob_type->tp_dict;\n// Recherche laborieuse du nom de la fonction en string", "blanks": [{"id": "1", "answer": "dict", "hint": "Nom logique du dictionnaire interne."}], "explanation": "Chaque objet Python doit transporter un dictionnaire (Hash Map) lourd pour permettre le typage dynamique."}},
    {"id": "ex-mod27-9", "type": "quiz", "question": "Que signifie le mot-clé 'final' en C++ (ou Java) ?", "difficulty": "hard", "xpReward": 50, "data": {"choices": [{"id": "a", "text": "Il interdit la surcharge (override) d'une méthode virtuelle par les enfants, permettant au compilateur de la transformer en appel direct (Devirtualization)."}, {"id": "b", "text": "Il ferme le fichier."}, {"id": "c", "text": "Il met la variable en lecture seule."}], "correctId": "a", "explanation": "C'est une optimisation monstrueuse : si on sait que personne n'héritera, on supprime la VTable et on gagne des cycles précieux."}},
    {"id": "ex-mod27-10", "type": "code-correction", "question": "Erreur d'héritage VTable", "difficulty": "hard", "xpReward": 50, "data": {"buggyCode": "class Base { public: void faire(); };\nclass Fille : public Base { public: void faire(); };\nBase* b = new Fille();\nb->faire(); // Appelle Base::faire", "correctCode": "class Base { public: virtual void faire(); };\nclass Fille : public Base { public: void faire() override; };", "hints": ["Il faut utiliser le mot-clé virtual."], "explanation": "Sans 'virtual', C++ utilise l'appel direct statique basé sur le type du pointeur (Base), et non le type réel de l'objet (Fille)."}}
])

# Write out the file
typescript_content = f"""import {{ Exercise, QuizData, FillBlankData, DragDropData, InteractiveLabData, CodeCorrectionData }} from '../../types';

export const demystificationExercises: Exercise[] = {json.dumps(exercises, indent=2)};
"""

# Replace dictionaries in `data` with casted types. We don't have to strictly do it if we cast the array as `any` but we will fix the strict typing.
import re

typescript_content = re.sub(r'(\s+)"data": ({{.*?}})', r'\1"data": \2 as any', typescript_content, flags=re.DOTALL)

with open('lib/content/exercises/demystification.ts', 'w', encoding='utf-8') as f:
    f.write(typescript_content)

print("Created 50 exercises successfully!")
