import json
import re

exercises = []

# --- MODULE 6 : Débogage avec GDB ---
exercises.extend([
    {"id": "ex-mod6-1", "type": "quiz", "question": "Pourquoi compiler avec le flag `-g` est-il essentiel pour le débogage avec GDB ?", "difficulty": "easy", "xpReward": 20, "data": {"choices": [{"id": "a", "text": "Pour que le programme s'exécute plus vite."}, {"id": "b", "text": "Pour inclure les symboles (noms de variables, numéros de lignes) afin que GDB lie l'assembleur au code source."}, {"id": "c", "text": "Pour utiliser la syntaxe Intel."}], "correctId": "b", "explanation": "Le flag `-g` génère la table DWARF. Sans elle, vous ne verrez que des adresses hexadécimales brutes."}},
    {"id": "ex-mod6-2", "type": "quiz", "question": "Dans GDB, que fait la commande `break main` (ou `b main`) ?", "difficulty": "easy", "xpReward": 20, "data": {"choices": [{"id": "a", "text": "Elle crashe le programme principal."}, {"id": "b", "text": "Elle met en pause le programme dès qu'il atteint le début de la fonction main()."}, {"id": "c", "text": "Elle ignore la fonction main()."}], "correctId": "b", "explanation": "C'est un Breakpoint (point d'arrêt). C'est la base du débogage."}},
    {"id": "ex-mod6-3", "type": "quiz", "question": "Quelle commande GDB permet de faire avancer l'exécution d'exactement UNE instruction assembleur (machine) ?", "difficulty": "medium", "xpReward": 30, "data": {"choices": [{"id": "a", "text": "next"}, {"id": "b", "text": "step"}, {"id": "c", "text": "stepi"}], "correctId": "c", "explanation": "`stepi` (Step Instruction) avance d'une instruction CPU. `step` avance d'une ligne de code C/C++ entière."}},
    {"id": "ex-mod6-4", "type": "fill-blank", "question": "Syntaxe GDB", "difficulty": "medium", "xpReward": 35, "data": {"codeTemplate": "(gdb) set disassembly-flavor __BLANK__\n(gdb) disassemble main", "blanks": [{"id": "1", "answer": "intel", "hint": "Pas AT&T."}], "explanation": "GDB utilise par défaut la syntaxe AT&T (illisible). 'intel' permet d'avoir la syntaxe standard (Destination, Source)."}},
    {"id": "ex-mod6-5", "type": "quiz", "question": "Comment afficher le contenu du registre RAX sous GDB ?", "difficulty": "medium", "xpReward": 30, "data": {"choices": [{"id": "a", "text": "print $rax"}, {"id": "b", "text": "cat rax"}, {"id": "c", "text": "show registers"}], "correctId": "a", "explanation": "Le préfixe '$' permet d'accéder aux registres CPU."}},
    {"id": "ex-mod6-6", "type": "quiz", "question": "Qu'est-ce qu'un 'Watchpoint' dans GDB ?", "difficulty": "hard", "xpReward": 50, "data": {"choices": [{"id": "a", "text": "Un point d'arrêt qui se déclenche dès que la valeur d'une VARIABLE en mémoire est modifiée."}, {"id": "b", "text": "Un chronomètre pour mesurer les performances."}, {"id": "c", "text": "Une vue graphique de la RAM."}], "correctId": "a", "explanation": "Idéal pour trouver 'Qui a écrasé ma variable globale ?' (ex: `watch my_var`). Le CPU utilise des registres de débogage matériels pour ça."}},
    {"id": "ex-mod6-7", "type": "drag-drop", "question": "Workflow GDB complet", "difficulty": "hard", "xpReward": 50, "data": {"items": [{"id": "1", "text": "gcc -g main.c (Compiler avec symboles)"}, {"id": "2", "text": "gdb ./a.out (Lancer GDB)"}, {"id": "3", "text": "break main (Mettre un point d'arrêt)"}, {"id": "4", "text": "run (Lancer l'exécution jusqu'au point d'arrêt)"}, {"id": "5", "text": "info registers (Inspecter l'état CPU)"}], "correctOrder": ["1", "2", "3", "4", "5"], "instruction": "Rangez les étapes d'une session de débogage parfaite.", "explanation": "Ne jamais lancer 'run' sans breakpoint, sinon le programme se termine d'un trait."}},
    {"id": "ex-mod6-8", "type": "fill-blank", "question": "Inspection de mémoire brutes", "difficulty": "hard", "xpReward": 50, "data": {"codeTemplate": "; Afficher 4 Entiers (Words) en format Hexa depuis l'adresse contenue dans RSP\n(gdb) x/__BLANK__ $rsp", "blanks": [{"id": "1", "answer": "4xw", "hint": "4 Hex Word."}], "explanation": "La commande 'x' (eXamine memory) est extrêmement puissante. 'x/4xw' signifie 4 valeurs, en heXadecimal, taille Word (32-bits)."}},
    {"id": "ex-mod6-9", "type": "quiz", "question": "Que signifie la commande GDB `layout asm` ?", "difficulty": "hard", "xpReward": 50, "data": {"choices": [{"id": "a", "text": "Elle modifie le code binaire en direct."}, {"id": "b", "text": "Elle ouvre une interface TUI (Text User Interface) graphique affichant le code assembleur en direct au-dessus du terminal."}, {"id": "c", "text": "Elle exporte l'assembleur dans un fichier."}], "correctId": "b", "explanation": "C'est la fonctionnalité qui rend GDB utilisable visuellement, montrant l'avancement de RIP ligne par ligne."}},
    {"id": "ex-mod6-10", "type": "code-correction", "question": "GDB Syntax Fix", "difficulty": "hard", "xpReward": 50, "data": {"buggyCode": "(gdb) break *main+10\n(gdb) play", "correctCode": "(gdb) break *main+10\n(gdb) run", "hints": ["La commande pour démarrer l'exécution est run."], "explanation": "Pour démarrer le programme, on utilise `run`. Pour avancer, `step` ou `next`. `play` n'existe pas."}}
])

# --- MODULE 7 : Optimisation bas niveau ---
exercises.extend([
    {"id": "ex-mod7-1", "type": "quiz", "question": "Pourquoi l'instruction cmov (Conditional Move) est-elle si prisée des compilateurs modernes (O3) ?", "difficulty": "easy", "xpReward": 20, "data": {"choices": [{"id": "a", "text": "Elle permet d'éviter un saut conditionnel, évitant le 'Branch Misprediction'."}, {"id": "b", "text": "Elle consomme moins de mémoire RAM."}, {"id": "c", "text": "Elle est multi-threadée."}], "correctId": "a", "explanation": "En évitant de sauter (jump), on ne brise pas le pipeline du CPU."}},
    {"id": "ex-mod7-2", "type": "quiz", "question": "Quelle technique de boucle consiste à dupliquer le code intérieur pour réduire le nombre de comparaisons (`cmp/jne`) ?", "difficulty": "easy", "xpReward": 20, "data": {"choices": [{"id": "a", "text": "Loop Unrolling (Déroulage de boucle)."}, {"id": "b", "text": "Loop Infinite."}, {"id": "c", "text": "Recursion."}], "correctId": "a", "explanation": "Faire 4 calculs par itération divise par 4 le surcoût de gestion de la boucle."}},
    {"id": "ex-mod7-3", "type": "quiz", "question": "Pourquoi l'instruction `lea` est-elle considérée comme un hack mathématique génial ?", "difficulty": "medium", "xpReward": 30, "data": {"choices": [{"id": "a", "text": "Elle effectue des calculs complexes (ex: a + b*4 + c) en un seul cycle d'horloge sans modifier les flags d'état (EFLAGS)."}, {"id": "b", "text": "Elle divise par zéro."}, {"id": "c", "text": "Elle efface le disque dur."}], "correctId": "a", "explanation": "C'est le couteau suisse de x86. C'est fait pour les adresses mémoire (Scale-Index-Base), mais utilisé pour l'arithmétique rapide."}},
    {"id": "ex-mod7-4", "type": "fill-blank", "question": "Multiplication par Bit-Shift", "difficulty": "medium", "xpReward": 35, "data": {"codeTemplate": "; Au lieu d'utiliser l'instruction 'mul' lente, multiplier EAX par 8 :\n__BLANK__ eax, 3", "blanks": [{"id": "1", "answer": "shl", "hint": "Shift Left."}], "explanation": "Décaler les bits vers la gauche (shl) de N positions équivaut à multiplier par 2^N. Donc shl par 3 = *8. C'est instantané."}},
    {"id": "ex-mod7-5", "type": "quiz", "question": "Qu'est-ce que l'Inlining ?", "difficulty": "medium", "xpReward": 30, "data": {"choices": [{"id": "a", "text": "Le remplacement d'un 'call' (appel de fonction) par la copie directe du code de la fonction dans l'appelant."}, {"id": "b", "text": "La suppression des variables globales."}, {"id": "c", "text": "L'écriture du code sur une seule ligne de texte."}], "correctId": "a", "explanation": "L'Inlining élimine totalement l'overhead d'une Stack Frame pour les petites fonctions."}},
    {"id": "ex-mod7-6", "type": "quiz", "question": "Pourquoi le parcours matriciel `[y][x]` est-il dramatiquement plus rapide que `[x][y]` en C++ ?", "difficulty": "hard", "xpReward": 50, "data": {"choices": [{"id": "a", "text": "À cause de la 'Localité Spatiale' du Cache CPU L1. Parcourir ligne par ligne lit la RAM de façon contiguë."}, {"id": "b", "text": "Parce que le C++ aime les x."}, {"id": "c", "text": "Parce que c'est une règle mathématique."}], "correctId": "a", "explanation": "Parcourir colonne par colonne (x puis y) saute des blocs de RAM, provoquant des Cache Miss destructeurs pour les performances."}},
    {"id": "ex-mod7-7", "type": "drag-drop", "question": "Optimisation des IFs (-O3)", "difficulty": "hard", "xpReward": 50, "data": {"items": [{"id": "1", "text": "Code C : if (a > b) max = a; else max = b;"}, {"id": "2", "text": "ASM non-optimisé : cmp a, b; jle else_bloc; mov max, a; jmp fin..."}, {"id": "3", "text": "ASM Optimisé (CMOV) : mov max, b; cmp a, b; cmova max, a"}, {"id": "4", "text": "Gain : Le pipeline CPU ne subit aucun Flush lié au saut."}], "correctOrder": ["1", "2", "3", "4"], "instruction": "Déroulez l'évolution d'une simple condition vers son état ultime.", "explanation": "Le CMOV (Conditional Move) est la signature de -O3."}},
    {"id": "ex-mod7-8", "type": "fill-blank", "question": "Strength Reduction", "difficulty": "hard", "xpReward": 50, "data": {"codeTemplate": "; L'optimisation 'Strength Reduction' remplace les opérations mathématiques coûteuses par des moins chères.\n; Remplacer une division par 2 (lente) :\n__BLANK__ eax, 1", "blanks": [{"id": "1", "answer": "shr", "hint": "Shift Right."}], "explanation": "Décaler à droite (shr) de 1 bit divise par 2 beaucoup plus rapidement qu'une instruction 'div'."}},
    {"id": "ex-mod7-9", "type": "quiz", "question": "Qu'est-ce que le 'Dead Code Elimination' ?", "difficulty": "hard", "xpReward": 50, "data": {"choices": [{"id": "a", "text": "Le compilateur supprime tout bloc de code, variable ou fonction dont les résultats ne sont jamais utilisés ou affichés."}, {"id": "b", "text": "Il supprime les erreurs de segmentation."}, {"id": "c", "text": "Il nettoie la RAM."}], "correctId": "a", "explanation": "Si vous faites un calcul de 3 milliards de boucles sans jamais faire de `printf` de la réponse, GCC (-O3) supprimera la boucle purement et simplement."}},
    {"id": "ex-mod7-10", "type": "code-correction", "question": "Élimination des invariants de boucle", "difficulty": "hard", "xpReward": 50, "data": {"buggyCode": "for(int i=0; i<100; i++) {\n  int val = x * y;\n  arr[i] = val + i;\n}", "correctCode": "int val = x * y;\nfor(int i=0; i<100; i++) {\n  arr[i] = val + i;\n}", "hints": ["Le produit x * y ne change pas pendant la boucle."], "explanation": "Le compilateur sortira l'opération `x * y` hors de la boucle pour ne pas la recalculer 100 fois. C'est le 'Loop Invariant Code Motion'."}}
])


# --- MODULE 8 : Le Frontend (Parseur, AST) ---
exercises.extend([
    {"id": "ex-mod8-1", "type": "quiz", "question": "Quel est le rôle du 'Lexer' (Analyseur Lexical) ?", "difficulty": "easy", "xpReward": 20, "data": {"choices": [{"id": "a", "text": "Transformer le texte source brut (lettres) en une suite de 'Tokens' (mots-clés, nombres, symboles)."}, {"id": "b", "text": "Générer du code assembleur."}, {"id": "c", "text": "Optimiser la RAM."}], "correctId": "a", "explanation": "Le Lexer simplifie le texte `int x = 5;` en tokens: `[TYPE_INT, IDENTIFIER('x'), ASSIGN, NUMBER(5), SEMICOLON]`."}},
    {"id": "ex-mod8-2", "type": "quiz", "question": "Qu'est-ce qu'un AST (Abstract Syntax Tree) ?", "difficulty": "easy", "xpReward": 20, "data": {"choices": [{"id": "a", "text": "Un Arbre représentant la structure hiérarchique et logique de votre code (blocs, opérateurs, opérandes)."}, {"id": "b", "text": "Un arbre en ASCII dans le terminal."}, {"id": "c", "text": "Un type de variable."}], "correctId": "a", "explanation": "C'est la carte mentale du programme, où `2 + 3 * 4` a le signe `+` à la racine, et `*` en branche droite (Priorité)."}},
    {"id": "ex-mod8-3", "type": "quiz", "question": "Dans l'expression `a = 5 * 2 + 3`, quel opérateur sera le plus profond dans l'AST ?", "difficulty": "medium", "xpReward": 30, "data": {"choices": [{"id": "a", "text": "Le signe `=`"}, {"id": "b", "text": "Le signe `*` (multiplication)"}, {"id": "c", "text": "Le signe `+`"}], "correctId": "b", "explanation": "La multiplication (5*2) doit être calculée en premier, elle est donc au fond de l'arbre pour remonter son résultat au `+`."}},
    {"id": "ex-mod8-4", "type": "fill-blank", "question": "Ordre de Compilation", "difficulty": "medium", "xpReward": 35, "data": {"codeTemplate": "Code Source -> __BLANK__ (Tokens) -> Parseur (__BLANK__) -> Génération IR", "blanks": [{"id": "1", "answer": "Lexer", "hint": "Celui qui fait l'analyse lexicale."}, {"id": "2", "answer": "AST", "hint": "L'arbre généré par le Parseur."}], "explanation": "C'est le flux standard du 'Frontend' de tout compilateur (Clang, GCC, Rustc)."}},
    {"id": "ex-mod8-5", "type": "quiz", "question": "À quoi sert la 'Table des Symboles' (Symbol Table) ?", "difficulty": "medium", "xpReward": 30, "data": {"choices": [{"id": "a", "text": "Stocker le nom de toutes les variables/fonctions déclarées, leur portée (scope) et leur type pour vérifier si elles existent (Semantic Analysis)."}, {"id": "b", "text": "Chiffrer le code."}, {"id": "c", "text": "Stocker les polices d'écriture."}], "correctId": "a", "explanation": "Sans elle, le compilateur ne saurait pas si `ma_variable` a été déclarée avant d'être utilisée."}},
    {"id": "ex-mod8-6", "type": "quiz", "question": "Pourquoi la création de compilateurs modernes est-elle souvent séparée en Frontend et Backend (ex: l'architecture LLVM) ?", "difficulty": "hard", "xpReward": 50, "data": {"choices": [{"id": "a", "text": "Pour que le Frontend (C++, Rust) produise une 'Langue Commune' (IR), et que le Backend la traduise pour la cible (x86, ARM), évitant de réécrire M Langages * N Architectures."}, {"id": "b", "text": "Parce qu'un seul développeur ne peut pas tout faire."}, {"id": "c", "text": "Pour ralentir la compilation."}], "correctId": "a", "explanation": "C'est le génie de LLVM : un nouveau langage (Swift) n'a qu'à écrire un Frontend produisant de l'IR LLVM, et il devient instantanément compatible avec tous les CPU du monde."}},
    {"id": "ex-mod8-7", "type": "drag-drop", "question": "Les Erreurs de Compilation", "difficulty": "hard", "xpReward": 50, "data": {"items": [{"id": "1", "text": "Lexical Error (ex: # au lieu de //)"}, {"id": "2", "text": "Syntax Error (ex: oubli d'un point-virgule)"}, {"id": "3", "text": "Semantic Error (ex: variable non déclarée, ou int = string)"}, {"id": "4", "text": "Linker Error (ex: fonction définie nulle part mais utilisée)"}], "correctOrder": ["1", "2", "3", "4"], "instruction": "Ordonnez le type d'erreur qui apparaîtra en premier lors du cycle de compilation complet.", "explanation": "L'erreur de Linker est toujours la dernière étape, car elle concerne l'assemblage des fichiers binaires."}},
    {"id": "ex-mod8-8", "type": "fill-blank", "question": "Backus-Naur Form (BNF)", "difficulty": "hard", "xpReward": 50, "data": {"codeTemplate": "; La grammaire d'un langage est souvent définie formellement en BNF.\n; Une expression peut être soit un nombre, soit une addition :\n<expr> ::= <number> | <expr> __BLANK__ <expr>", "blanks": [{"id": "1", "answer": "+", "hint": "Opérateur d'addition."}], "explanation": "Cette définition récursive permet au Parseur de comprendre l'emboîtement infini des parenthèses."}},
    {"id": "ex-mod8-9", "type": "quiz", "question": "Qu'est-ce que le 'Recursive Descent Parsing' (Analyse descendante récursive) ?", "difficulty": "hard", "xpReward": 50, "data": {"choices": [{"id": "a", "text": "La méthode la plus courante pour écrire un parseur à la main, où chaque règle de grammaire devient une fonction qui appelle les autres règles."}, {"id": "b", "text": "Une technique d'IA."}, {"id": "c", "text": "Un plongeon récursif."}], "correctId": "a", "explanation": "C'est l'approche utilisée par GCC et Clang pour construire l'AST. C'est intuitif et très rapide."}},
    {"id": "ex-mod8-10", "type": "code-correction", "question": "AST Récursivité", "difficulty": "hard", "xpReward": 50, "data": {"buggyCode": "if(token == NUMBER) { return parse_number(); }\nif(token == PLUS) { return parse_plus(); }", "correctCode": "Node* left = parse_number();\nif(token == PLUS) { return parse_binary_op(left, PLUS); }", "hints": ["L'opérateur '+' doit prendre l'élément gauche (déjà parsé) avec lui."], "explanation": "Un AST binaire (gauche/droite) se construit en englobant les nœuds précédents sous le nouveau nœud opérateur (le PLUS devient la racine)."}}
])


# --- MODULE 9 : L'IR (Représentation Intermédiaire) ---
exercises.extend([
    {"id": "ex-mod9-1", "type": "quiz", "question": "Que signifie 'IR' dans un compilateur ?", "difficulty": "easy", "xpReward": 20, "data": {"choices": [{"id": "a", "text": "Intermediate Representation (Représentation Intermédiaire)."}, {"id": "b", "text": "Internal Register."}, {"id": "c", "text": "Information Retrieval."}], "correctId": "a", "explanation": "C'est un langage Assembleur 'abstrait', mathématiquement pur, indépendant de toute machine."}},
    {"id": "ex-mod9-2", "type": "quiz", "question": "Que signifie la forme 'SSA' (Static Single Assignment) de l'IR LLVM ?", "difficulty": "easy", "xpReward": 20, "data": {"choices": [{"id": "a", "text": "Chaque variable 'virtuelle' (ex: %1, %2) n'est assignée (modifiée) qu'UNE seule fois."}, {"id": "b", "text": "Il n'y a pas de variables."}, {"id": "c", "text": "Tout est statique."}], "correctId": "a", "explanation": "Cette contrainte stricte permet aux algorithmes d'optimisation (le Middle-End) de fonctionner magiquement vite."}},
    {"id": "ex-mod9-3", "type": "quiz", "question": "Combien de 'registres' virtuels (variables) sont autorisés dans une IR LLVM ?", "difficulty": "medium", "xpReward": 30, "data": {"choices": [{"id": "a", "text": "16 comme x86-64."}, {"id": "b", "text": "Une infinité (%1, %2, %9999...)."}, {"id": "c", "text": "Aucun."}], "correctId": "b", "explanation": "L'IR n'est pas limité par la réalité physique. C'est le Backend qui devra ensuite 'caser' ces millions de registres virtuels dans les 16 registres physiques (Register Allocation)."}},
    {"id": "ex-mod9-4", "type": "fill-blank", "question": "IR LLVM Typée", "difficulty": "medium", "xpReward": 35, "data": {"codeTemplate": "; L'IR LLVM est fortement typée (contrairement à l'ASM pur).\n; Additionner deux entiers 32 bits:\n%3 = add __BLANK__ %1, %2", "blanks": [{"id": "1", "answer": "i32", "hint": "Integer 32 bits."}], "explanation": "L'IR garde trace des types (i32, i64, float) pour générer l'assembleur correct plus tard."}},
    {"id": "ex-mod9-5", "type": "quiz", "question": "Pourquoi traduire l'AST en IR linéaire ?", "difficulty": "medium", "xpReward": 30, "data": {"choices": [{"id": "a", "text": "Parce qu'un Arbre (AST) est complexe à optimiser mathématiquement. Une suite d'instructions linéaires simples (IR) se manipule et s'optimise comme du code machine abstrait."}, {"id": "b", "text": "Pour faire beau."}, {"id": "c", "text": "Parce qu'on ne peut pas compiler un arbre."}], "correctId": "a", "explanation": "L'IR ressemble à de l'assembleur, ce qui prépare parfaitement le terrain pour l'étape du Backend."}},
    {"id": "ex-mod9-6", "type": "quiz", "question": "Qu'est-ce qu'une fonction Phi (`phi`) en SSA ?", "difficulty": "hard", "xpReward": 50, "data": {"choices": [{"id": "a", "text": "Une instruction magique qui sélectionne la bonne version d'une variable en fonction du bloc (If/Else) par lequel l'exécution est passée."}, {"id": "b", "text": "Un calcul mathématique Pi (3.14)."}, {"id": "c", "text": "Une erreur."}], "correctId": "a", "explanation": "Puisqu'on ne peut assigner une variable qu'une seule fois en SSA, `phi` permet de résoudre les collisions de variables après des branchements divergents."}},
    {"id": "ex-mod9-7", "type": "drag-drop", "question": "Génération de Code 3-Adresses", "difficulty": "hard", "xpReward": 50, "data": {"items": [{"id": "1", "text": "AST: x = (a + b) * c"}, {"id": "2", "text": "IR 1: %1 = add i32 %a, %b"}, {"id": "3", "text": "IR 2: %2 = mul i32 %1, %c"}, {"id": "4", "text": "IR 3: store i32 %2, i32* %x"}], "correctOrder": ["1", "2", "3", "4"], "instruction": "Déroulez l'aplatissement (flattening) d'une expression complexe en code à 3-Adresses (Résultat = Opérande1, Opérande2).", "explanation": "Chaque opération devient une instruction unitaire stricte."}},
    {"id": "ex-mod9-8", "type": "fill-blank", "question": "Basic Blocks (Blocs de Base)", "difficulty": "hard", "xpReward": 50, "data": {"codeTemplate": "; Un bloc de base (Basic Block) dans un graphe de contrôle (CFG)\n; a un seul point d'entrée, et un seul point de __BLANK__ (ex: br, ret).\nLabel1:\n  %1 = add i32 1, 1\n  __BLANK__ label %Label2", "blanks": [{"id": "1", "answer": "sortie", "hint": "Exit point."}, {"id": "2", "answer": "br", "hint": "Instruction Branch (saut)."}], "explanation": "L'IR découpe tout le code en blocs séquentiels purs connectés par des branches. Cela forme un Control Flow Graph (CFG)."}},
    {"id": "ex-mod9-9", "type": "quiz", "question": "En LLVM IR, pourquoi manipule-t-on souvent les pointeurs locaux avec `alloca` au lieu de créer directement des registres virtuels SSA pour les variables mutables ?", "difficulty": "hard", "xpReward": 50, "data": {"choices": [{"id": "a", "text": "Pour simuler de la mémoire locale (la pile) et contourner l'interdiction de muter une variable SSA (la variable pointe vers une RAM mutable)."}, {"id": "b", "text": "Parce que alloca est plus rapide."}, {"id": "c", "text": "Pour faire des allocations sur le tas."}], "correctId": "a", "explanation": "Plus tard, l'optimisation SROA (Scalar Replacement of Aggregates) transformera ces alloca lents en registres purs SSA si possible."}},
    {"id": "ex-mod9-10", "type": "code-correction", "question": "Erreur SSA", "difficulty": "hard", "xpReward": 50, "data": {"buggyCode": "%1 = add i32 %a, 5\n%1 = mul i32 %1, 2", "correctCode": "%1 = add i32 %a, 5\n%2 = mul i32 %1, 2", "hints": ["En SSA, une variable (%1) ne peut être assignée qu'UNE FOIS."], "explanation": "C'est la règle d'or de l'IR LLVM : créer une nouvelle version de variable à chaque modification."}}
])


# --- MODULE 10 : Le Middle-End (Optimisations IR) ---
exercises.extend([
    {"id": "ex-mod10-1", "type": "quiz", "question": "Que fait l'optimisation 'Constant Folding' (Pliage de Constantes) ?", "difficulty": "easy", "xpReward": 20, "data": {"choices": [{"id": "a", "text": "Elle calcule les expressions mathématiques simples à la compilation (ex: 5 * 2 + 10 -> 20) pour que le CPU n'ait pas à le faire."}, {"id": "b", "text": "Elle chiffre les constantes."}, {"id": "c", "text": "Elle réduit la taille de l'écran."}], "correctId": "a", "explanation": "Le compilateur fait les maths à votre place."}},
    {"id": "ex-mod10-2", "type": "quiz", "question": "Que fait l'optimisation 'Dead Code Elimination' (DCE) ?", "difficulty": "easy", "xpReward": 20, "data": {"choices": [{"id": "a", "text": "Elle supprime le code injoignable (après un return) ou les calculs dont le résultat n'est jamais utilisé/retourné."}, {"id": "b", "text": "Elle ferme le programme."}, {"id": "c", "text": "Elle efface les commentaires."}], "correctId": "a", "explanation": "C'est ce qui fait que des boucles énormes vides sont transformées en RIEN par -O3."}},
    {"id": "ex-mod10-3", "type": "quiz", "question": "Qu'est-ce que l'optimisation 'Loop Unrolling' (Déroulage de boucle) ?", "difficulty": "medium", "xpReward": 30, "data": {"choices": [{"id": "a", "text": "Répéter le corps de la boucle plusieurs fois en dur pour réduire le nombre total de comparaisons/sauts (overhead)."}, {"id": "b", "text": "Transformer une boucle en appel de fonction."}, {"id": "c", "text": "Mettre la boucle à l'envers."}], "correctId": "a", "explanation": "Le fichier binaire grossit (plus d'instructions), mais le CPU tourne beaucoup plus vite."}},
    {"id": "ex-mod10-4", "type": "fill-blank", "question": "Constant Propagation", "difficulty": "medium", "xpReward": 35, "data": {"codeTemplate": "; Avant : \n; int x = 10; \n; return x * 2;\n\n; Après Constant Propagation & Folding (Middle-end) :\nreturn __BLANK__;", "blanks": [{"id": "1", "answer": "20", "hint": "Le résultat final compilé."}], "explanation": "La variable x est traquée, sa constante propagée, puis pliée (Folding)."}},
    {"id": "ex-mod10-5", "type": "quiz", "question": "Qu'est-ce que l'Inline Expansion (Inlining) de fonction ?", "difficulty": "medium", "xpReward": 30, "data": {"choices": [{"id": "a", "text": "Remplacer l'appel à une fonction (call) par le code entier de la fonction, évitant le coût d'une Frame."}, {"id": "b", "text": "Mettre le texte en ligne."}, {"id": "c", "text": "Changer le type de retour."}], "correctId": "a", "explanation": "C'est l'optimisation la plus importante du C++ (qui justifie le Zero-Overhead des getters/setters)."}},
    {"id": "ex-mod10-6", "type": "quiz", "question": "Pourquoi l'optimisation 'LICM' (Loop Invariant Code Motion) est-elle cruciale ?", "difficulty": "hard", "xpReward": 50, "data": {"choices": [{"id": "a", "text": "Elle sort les calculs qui ne changent pas (invariants) en dehors de la boucle pour ne pas les refaire à chaque itération."}, {"id": "b", "text": "Elle inverse les boucles."}, {"id": "c", "text": "Elle supprime la boucle."}], "correctId": "a", "explanation": "Exemple: si vous faites `a = x * 2` dans un `for(i=0...100)`, le compilateur mettra `a = x * 2` avant le `for`."}},
    {"id": "ex-mod10-7", "type": "drag-drop", "question": "La cascade des Optimisations LLVM", "difficulty": "hard", "xpReward": 50, "data": {"items": [{"id": "1", "text": "Inlining (Ramène le code des petites fonctions à l'intérieur)"}, {"id": "2", "text": "Constant Propagation & Folding (Résout les maths statiques exposées par l'inlining)"}, {"id": "3", "text": "Dead Code Elimination (Supprime les conditions If(false) résolues au-dessus)"}, {"id": "4", "text": "Vectorization (Transforme les boucles épurées restantes en SIMD)"}], "correctOrder": ["1", "2", "3", "4"], "instruction": "Les 'Passes' d'optimisation se nourrissent les unes des autres. Rangez-les logiquement.", "explanation": "Cette synergie (Passes) fait toute la magie d'un bon compilateur (-O3)."}},
    {"id": "ex-mod10-8", "type": "fill-blank", "question": "Common Subexpression Elimination (CSE)", "difficulty": "hard", "xpReward": 50, "data": {"codeTemplate": "; CSE : Si le compilateur voit 'y = a * b' puis 'z = a * b' plus loin,\n; Il supprime le 2ème calcul et fait simplement : \nz = __BLANK__", "blanks": [{"id": "1", "answer": "y", "hint": "Il réutilise le résultat précédent."}], "explanation": "L'IR stocke le graphe des valeurs. Si un nœud a la même entrée, il fusionne les nœuds (GPN)."}},
    {"id": "ex-mod10-9", "type": "quiz", "question": "En quoi consiste la vectorisation automatique (Auto-Vectorization) du Middle-End ?", "difficulty": "hard", "xpReward": 50, "data": {"choices": [{"id": "a", "text": "Il détecte une boucle traitant un tableau séquentiel et la remplace par des blocs d'opérations SIMD (ex: vaddps)."}, {"id": "b", "text": "Il crée des vecteurs C++ dynamiquement."}, {"id": "c", "text": "Il dessine des vecteurs."}], "correctId": "a", "explanation": "C'est le Graal de l'optimisation moderne, rendant le code jusqu'à 16x plus rapide sans changer une ligne de C."}},
    {"id": "ex-mod10-10", "type": "code-correction", "question": "Aliasing Pointers", "difficulty": "hard", "xpReward": 50, "data": {"buggyCode": "void add(int* a, int* b) {\n  for(int i=0; i<100; i++) {\n    *a += *b;\n  }\n}", "correctCode": "void add(int* restrict a, int* restrict b) {\n  // Sans 'restrict', le compilateur craint que 'a' et 'b' pointent \n  // vers la même adresse mémoire (Aliasing) et n'optimisera pas.\n}", "hints": ["Mot-clé magique C99 pour promettre qu'il n'y a pas d'aliasing."], "explanation": "Si `a == b`, chaque `*a += *b` modifie la cible de `b`. Le compilateur ne peut donc pas mettre `*b` en cache registre (ou vectoriser). `restrict` résout ce problème."}}
])

# --- MODULE 11 : Le Backend (Génération ASM) ---
exercises.extend([
    {"id": "ex-mod11-1", "type": "quiz", "question": "Quelle est la tâche principale du Backend LLVM/GCC ?", "difficulty": "easy", "xpReward": 20, "data": {"choices": [{"id": "a", "text": "Traduire l'IR abstraite optimisée en un véritable code Assembleur (x86, ARM, RISC-V) propre au processeur cible."}, {"id": "b", "text": "Compiler le code en Python."}, {"id": "c", "text": "Créer le fichier source C."}], "correctId": "a", "explanation": "Le Backend se charge de la réalité physique (Registres limités, architecture matérielle)."}},
    {"id": "ex-mod11-2", "type": "quiz", "question": "Comment s'appelle le processus d'assigner l'infinité de variables de l'IR (%1, %2...) aux 16 registres réels de x86-64 ?", "difficulty": "easy", "xpReward": 20, "data": {"choices": [{"id": "a", "text": "Register Allocation (Allocation de registres)."}, {"id": "b", "text": "Variable Sorting."}, {"id": "c", "text": "Garbage Collection."}], "correctId": "a", "explanation": "C'est l'un des algorithmes les plus complexes de l'informatique (coloration de graphes)."}},
    {"id": "ex-mod11-3", "type": "quiz", "question": "Que se passe-t-il lors de l'Allocation de Registres s'il y a plus de 'Variables Vivantes' que de registres physiques ?", "difficulty": "medium", "xpReward": 30, "data": {"choices": [{"id": "a", "text": "Le Backend effectue un 'Register Spilling' : il 'déverse' l'excédent sur la pile (RAM) (très lent)."}, {"id": "b", "text": "Il crashe."}, {"id": "c", "text": "Il supprime les variables."}], "correctId": "a", "explanation": "C'est pourquoi écrire des fonctions gigantesques avec 100 variables locales détruit les performances."}},
    {"id": "ex-mod11-4", "type": "fill-blank", "question": "Instruction Selection", "difficulty": "medium", "xpReward": 35, "data": {"codeTemplate": "; Le Backend utilise la 'Sélection d'Instruction'.\n; Par exemple, traduire `%3 = mul i32 %1, 8` vers :\n__BLANK__ eax, 3", "blanks": [{"id": "1", "answer": "shl", "hint": "Instruction spécifique x86 (Shift Left) au lieu de mul."}], "explanation": "Le Backend connaît les astuces intimes de l'architecture cible pour produire le code le plus rapide."}},
    {"id": "ex-mod11-5", "type": "quiz", "question": "Qu'est-ce que le 'Peephole Optimization' (Optimisation par le trou de serrure) ?", "difficulty": "medium", "xpReward": 30, "data": {"choices": [{"id": "a", "text": "Une passe finale du Backend qui regarde 2-3 instructions assembleur générées et les remplace par un motif plus court (ex: 'mov eax, 0' devient 'xor eax, eax')."}, {"id": "b", "text": "Regarder le code source de loin."}, {"id": "c", "text": "Cacher le code binaire."}], "correctId": "a", "explanation": "C'est un nettoyage microscopique de toute dernière minute sur le texte Assembleur final."}},
    {"id": "ex-mod11-6", "type": "quiz", "question": "Quel algorithme est couramment utilisé pour l'Allocation de Registres optimale ?", "difficulty": "hard", "xpReward": 50, "data": {"choices": [{"id": "a", "text": "La Coloration de Graphe (Graph Coloring)."}, {"id": "b", "text": "Le Tri à Bulles."}, {"id": "c", "text": "A-Star."}], "correctId": "a", "explanation": "Si 2 variables sont 'vivantes' en même temps, elles sont reliées. On tente de colorier le graphe entier avec K couleurs (les K registres CPU)."}},
    {"id": "ex-mod11-7", "type": "drag-drop", "question": "Workflow complet du Backend", "difficulty": "hard", "xpReward": 50, "data": {"items": [{"id": "1", "text": "Instruction Selection (Choix des Opcodes CPU cibles, ex: x86)"}, {"id": "2", "text": "Instruction Scheduling (Réordonner pour éviter les pipeline stalls CPU)"}, {"id": "3", "text": "Register Allocation (Coloration de Graphes et Spilling)"}, {"id": "4", "text": "Peephole Opt / Code Emission (Génération des bits finaux / Fichier Objet .o)"}], "correctOrder": ["1", "2", "3", "4"], "instruction": "Rangez les 4 étapes vitales du travail du Backend LLVM/GCC.", "explanation": "L'ordre d'exécution détermine grandement la vitesse du binaire (ex: l'allocation dépend de l'ordre schedulé)."}},
    {"id": "ex-mod11-8", "type": "fill-blank", "question": "Liveness Analysis (Analyse de vivacité)", "difficulty": "hard", "xpReward": 50, "data": {"codeTemplate": "; L'analyse de 'Liveness' détermine à quel moment une variable peut être écrasée par une autre pour recycler son registre.\n; Une variable est 'vivante' depuis sa déclaration jusqu'à sa dernière __BLANK__.", "blanks": [{"id": "1", "answer": "utilisation", "hint": "Lecture (Use)."}], "explanation": "Dès qu'une variable n'est plus lue plus bas dans le code, son registre physique est libre pour quelqu'un d'autre."}},
    {"id": "ex-mod11-9", "type": "quiz", "question": "Qu'est-ce que le 'Link Time Optimization' (LTO) ?", "difficulty": "hard", "xpReward": 50, "data": {"choices": [{"id": "a", "text": "Une technique où le compilateur génère non pas de l'assembleur pur, mais un fichier binaire hybride IR/Objet, permettant au Linker final (qui a la vue sur TOUS les fichiers .o du projet) d'Inliner massivement entre différents fichiers C++."}, {"id": "b", "text": "Le fait de supprimer les liens externes."}, {"id": "c", "text": "Optimiser le téléchargement d'un lien."}], "correctId": "a", "explanation": "Sans LTO, l'optimisation s'arrête aux frontières du fichier.h/.cpp. Avec LTO, la vue globale permet un gain drastique de vitesse."}},
    {"id": "ex-mod11-10", "type": "code-correction", "question": "Linker Error classique", "difficulty": "hard", "xpReward": 50, "data": {"buggyCode": "// Fichier A.cpp\nextern int globale;\nint main() { return globale; }", "correctCode": "// Fichier A.cpp\nextern int globale;\nint main() { return globale; }\n\n// Dans un autre fichier (B.cpp)\nint globale = 42;", "hints": ["L'erreur de linker 'Undefined reference' survient quand un symbole extern n'existe nulle part physiquement."], "explanation": "Le Backend a produit A.o sans erreur. C'est le Linker (Éditeur de liens) qui plante car il ne trouve pas l'adresse physique de la variable globale 'globale' dans les autres fichiers Objets."}}
])

# Write out the file
typescript_content = f"""import {{ Exercise, QuizData, FillBlankData, DragDropData, InteractiveLabData, CodeCorrectionData }} from '../../types';

export const intermediateExercises: Exercise[] = {json.dumps(exercises, indent=2)};
"""

# Type casting
typescript_content = re.sub(r'(\s+)"data": ({{.*?}})', r'\1"data": \2 as any', typescript_content, flags=re.DOTALL)

with open('lib/content/exercises/intermediate.ts', 'w', encoding='utf-8') as f:
    f.write(typescript_content)

print("Created 60 intermediate exercises successfully!")
