import json

exercises = []

# Mod 23 : Typage & RAM (10 exercices: 5 Hard, 3 Medium, 2 Easy)
exercises.extend([
    # EASY
    {"id": "ex-mod23-1", "type": "quiz", "question": "Combien d'octets prend un int standard en C++ (sur 32/64 bits) par rapport à un entier Python ?", "difficulty": "easy", "xpReward": 20, "data": {"choices": [{"id": "a", "text": "4 octets en C++ contre ~28 octets en Python"}, {"id": "b", "text": "8 octets pour les deux"}, {"id": "c", "text": "Python ne prend pas de RAM"}], "correctId": "a", "explanation": "Un int C++ est brut. Un int Python est un objet (PyLongObject)."}},
    {"id": "ex-mod23-2", "type": "quiz", "question": "Les entiers en Python sont immuables. Qu'est-ce que cela signifie ?", "difficulty": "easy", "xpReward": 20, "data": {"choices": [{"id": "a", "text": "On ne peut pas les additionner."}, {"id": "b", "text": "Chaque modification (ex: a = a + 1) crée un nouvel objet en mémoire."}, {"id": "c", "text": "Ils ne peuvent pas être négatifs."}], "correctId": "b", "explanation": "Python alloue un nouveau PyObject à chaque calcul, ce qui sollicite le tas (Heap) et le Garbage Collector."}},
    
    # MEDIUM
    {"id": "ex-mod23-3", "type": "quiz", "question": "Qu'est-ce que le 'Garbage Collector' (GC) fait concrètement en Python ?", "difficulty": "medium", "xpReward": 30, "data": {"choices": [{"id": "a", "text": "Il nettoie le cache du CPU."}, {"id": "b", "text": "Il détruit les objets du Tas dont le 'Reference Count' tombe à zéro."}, {"id": "c", "text": "Il compile le code."}], "correctId": "b", "explanation": "Le GC de Python (CPython) fonctionne principalement par comptage de références."}},
    {"id": "ex-mod23-4", "type": "fill-blank", "question": "L'en-tête d'un objet Python", "difficulty": "medium", "xpReward": 35, "data": {"codeTemplate": "struct PyObject {\n  Py_ssize_t __BLANK__; // Compteur de références\n  struct _typeobject *__BLANK__; // Pointeur vers le type\n};", "blanks": [{"id": "1", "answer": "ob_refcnt", "hint": "Le compteur (Reference Count)."}, {"id": "2", "answer": "ob_type", "hint": "Le pointeur de type."}], "explanation": "C'est l'en-tête minimal de tout objet Python, pesant déjà 16 octets."}},
    {"id": "ex-mod23-5", "type": "quiz", "question": "Dans un std::vector C++, où se trouvent les éléments ?", "difficulty": "medium", "xpReward": 30, "data": {"choices": [{"id": "a", "text": "Répartis aléatoirement dans la RAM."}, {"id": "b", "text": "Dans un bloc de mémoire strictement contigu sur le Tas."}, {"id": "c", "text": "Dans le cache L3 uniquement."}], "correctId": "b", "explanation": "La contiguïté est ce qui rend le vector si rapide à parcourir."}},

    # HARD
    {"id": "ex-mod23-6", "type": "quiz", "question": "Pourquoi la contiguïté mémoire empêche-t-elle le 'Cache Miss' ?", "difficulty": "hard", "xpReward": 50, "data": {"choices": [{"id": "a", "text": "Parce que le CPU charge la mémoire par 'lignes de cache' (ex: 64 octets d'un coup)."}, {"id": "b", "text": "Parce que le CPU désactive le cache."}, {"id": "c", "text": "Parce que la RAM tourne plus vite."}], "correctId": "a", "explanation": "Si les données sont contiguës, charger un élément charge aussi les suivants dans le cache très rapide (L1)."}},
    {"id": "ex-mod23-7", "type": "drag-drop", "question": "Ordonnez ces accès mémoire du plus rapide au plus lent.", "difficulty": "hard", "xpReward": 50, "data": {"items": [{"id": "1", "text": "Registre (RAX)"}, {"id": "2", "text": "Cache L1"}, {"id": "3", "text": "RAM (Tas)"}, {"id": "4", "text": "SSD (Swap)"}], "correctOrder": ["1", "2", "3", "4"], "explanation": "Les registres prennent 1 cycle, le L1 ~4 cycles, la RAM ~300 cycles, le SSD des millions."}},
    {"id": "ex-mod23-8", "type": "fill-blank", "question": "Accès Scale-Index-Base (SIB)", "difficulty": "hard", "xpReward": 50, "data": {"codeTemplate": "; Lire le 5ème int d'un vector (index 4)\nmov rcx, 4\nmov eax, [rbx + __BLANK__ * __BLANK__]", "blanks": [{"id": "1", "answer": "rcx", "hint": "Le registre d'index."}, {"id": "2", "answer": "4", "hint": "La taille d'un entier en octets."}], "explanation": "Le SIB permet de calculer instantanément l'adresse d'un élément dans un tableau en hardware."}},
    {"id": "ex-mod23-9", "type": "quiz", "question": "Pourquoi une liste Python est-elle un tableau de pointeurs et non de valeurs ?", "difficulty": "hard", "xpReward": 50, "data": {"choices": [{"id": "a", "text": "Pour économiser de la RAM."}, {"id": "b", "text": "Pour permettre le polymorphisme (stocker des types différents dans la même liste)."}, {"id": "c", "text": "Pour éviter d'utiliser des pointeurs."}], "correctId": "b", "explanation": "Comme les objets Python ont des tailles différentes, la liste ne stocke que leurs adresses (8 octets chacune), ce qui nécessite un double déréférencement à la lecture."}},
    {"id": "ex-mod23-10", "type": "fill-blank", "question": "Le coût du polymorphisme Python en ASM", "difficulty": "hard", "xpReward": 50, "data": {"codeTemplate": "mov __BLANK__, [rbx + rcx * 8] ; 1. Lire le pointeur de la liste\nmov rax, [__BLANK__ + 24] ; 2. Déréférencer l'objet pour lire sa valeur", "blanks": [{"id": "1", "answer": "rdx", "hint": "Registre temporaire."}, {"id": "2", "answer": "rdx", "hint": "On déréférence ce registre."}], "explanation": "Ce double accès mémoire (pointer chasing) détruit la localité spatiale et provoque des Cache Miss."}},
])

# Mod 24 : Contrôle de flux (10 exercices: 5 Hard, 3 Medium, 2 Easy)
exercises.extend([
    # EASY
    {"id": "ex-mod24-1", "type": "quiz", "question": "Que signifie le 'Dynamic Dispatch' ?", "difficulty": "easy", "xpReward": 20, "data": {"choices": [{"id": "a", "text": "L'appel de fonction est décidé à l'exécution (runtime)."}, {"id": "b", "text": "Le compilateur supprime la fonction."}, {"id": "c", "text": "L'appel est résolu à la compilation."}], "correctId": "a", "explanation": "En Python, on ne sait pas quelle méthode __eq__ appeler avant de vérifier le type exact de l'objet à l'exécution."}},
    {"id": "ex-mod24-2", "type": "quiz", "question": "Comment le compilateur C++ traduit-il une simple condition (a == b) ?", "difficulty": "easy", "xpReward": 20, "data": {"choices": [{"id": "a", "text": "En cherchant une méthode __eq__."}, {"id": "b", "text": "Par une instruction 'cmp' suivie d'un saut ('je')."}, {"id": "c", "text": "Il délègue ça au système d'exploitation."}], "correctId": "b", "explanation": "C++ produit le code machine le plus direct et minimaliste."}},

    # MEDIUM
    {"id": "ex-mod24-3", "type": "quiz", "question": "Qu'est-ce qu'une Frame (Cadre de pile) ?", "difficulty": "medium", "xpReward": 30, "data": {"choices": [{"id": "a", "text": "Une image vidéo du jeu."}, {"id": "b", "text": "Une zone sur la pile contenant les variables locales et l'adresse de retour d'une fonction."}, {"id": "c", "text": "Un bloc de mémoire sur le tas."}], "correctId": "b", "explanation": "À chaque appel de fonction, une Stack Frame est créée. Elle est détruite au 'ret'."}},
    {"id": "ex-mod24-4", "type": "fill-blank", "question": "Le saut de Dynamic Dispatch en Python", "difficulty": "medium", "xpReward": 35, "data": {"codeTemplate": "call PyObject_RichCompare\n; Cette lourde fonction C va lire le dictionnaire de la classe\n; pour trouver le pointeur de la fonction __BLANK__", "blanks": [{"id": "1", "answer": "__eq__", "hint": "Méthode spéciale d'égalité."}], "explanation": "Là où C++ fait un 'cmp', Python fait un appel de fonction complet et une recherche dans une table de hachage."}},
    {"id": "ex-mod24-5", "type": "quiz", "question": "Comment fonctionnent les Générateurs (yield) en Python ?", "difficulty": "medium", "xpReward": 30, "data": {"choices": [{"id": "a", "text": "Ils sauvegardent l'état (Stack Frame) sur le Tas pour y revenir plus tard."}, {"id": "b", "text": "Ils bloquent le CPU dans une boucle infinie."}, {"id": "c", "text": "Ils compilent le code en temps réel."}], "correctId": "a", "explanation": "Au lieu de détruire la frame, elle est suspendue et conservée en RAM."}},

    # HARD
    {"id": "ex-mod24-6", "type": "quiz", "question": "En C++20, comment les Coroutines (co_yield) gèrent-elles leur pile ?", "difficulty": "hard", "xpReward": 50, "data": {"choices": [{"id": "a", "text": "C++ utilise une 'Stackless Coroutine', allouant dynamiquement un petit bloc d'état sur le tas."}, {"id": "b", "text": "Elles utilisent des Threads de l'OS."}, {"id": "c", "text": "Elles copient toute la RAM."}], "correctId": "a", "explanation": "Pour ne pas bloquer de Threads, C++ alloue juste ce qu'il faut sur le tas (Heap) pour reprendre l'exécution (Instruction Pointer + variables capturées)."}},
    {"id": "ex-mod24-7", "type": "fill-blank", "question": "L'inlining", "difficulty": "hard", "xpReward": 50, "data": {"codeTemplate": "; Au lieu de :\n; call ma_fonction_courte\n; Le compilateur fait du __BLANK__ en copiant directement les instructions.", "blanks": [{"id": "1", "answer": "inlining", "hint": "Intégration en ligne (Inline)."}], "explanation": "L'inlining évite le coût de création de Stack Frame pour les petites fonctions. Python ne peut presque jamais le faire à cause du typage dynamique."}},
    {"id": "ex-mod24-8", "type": "drag-drop", "question": "Ordre de résolution d'une méthode virtuelle en C++ (VTable).", "difficulty": "hard", "xpReward": 50, "data": {"items": [{"id": "1", "text": "Lire le pointeur vptr caché dans l'objet"}, {"id": "2", "text": "Lire l'adresse de la fonction à l'offset désiré dans la VTable"}, {"id": "3", "text": "Sauter (call) à cette adresse"}], "correctOrder": ["1", "2", "3"], "explanation": "C++ résout le polymorphisme avec un double déréférencement de pointeur pré-calculé, ce qui prend ~3 cycles CPU contre ~100 pour Python."}},
    {"id": "ex-mod24-9", "type": "quiz", "question": "Pourquoi le Branch Predictor (Prédiction de branchement) aime le C++ plus que Python ?", "difficulty": "hard", "xpReward": 50, "data": {"choices": [{"id": "a", "text": "Parce que Python utilise des sauts indirects massifs (appels de pointeurs de fonctions variables) très difficiles à deviner pour le CPU."}, {"id": "b", "text": "Parce que C++ est écrit en anglais."}, {"id": "c", "text": "Parce que Python ne fait pas de sauts."}], "correctId": "a", "explanation": "L'interpréteur Python est une boucle massive avec un grand switch (sauts indirects). Le CPU se trompe souvent, vidant son pipeline."}},
    {"id": "ex-mod24-10", "type": "code-correction", "question": "Optimisez ce code pseudo-ASM qui prépare un appel de méthode. Utilisez l'instruction appropriée pour un appel indirect.", "difficulty": "hard", "xpReward": 50, "data": {"buggyCode": "mov rax, [vtable_ptr]\njmp [rax]", "correctCode": "mov rax, [vtable_ptr]\ncall [rax]", "hints": ["On veut pouvoir revenir de la méthode !"], "explanation": "Une méthode virtuelle nécessite un 'call' pour que l'adresse de retour soit poussée sur la pile, et non un 'jmp' définitif."}},
])

# Generate output
typescript_content = f"""import {{ Exercise, QuizData, FillBlankData, DragDropData, InteractiveLabData, CodeCorrectionData }} from '../../types';

export const demystificationExercises: Exercise[] = {json.dumps(exercises, indent=2)};
"""

# Replace the "type": "..." string values back into correct Enums or fix json serialization if needed.
# However, TypeScript will cast the JSON nicely if we just add 'as QuizData' where needed, but it's easier to just cast the whole array.
typescript_content = typescript_content.replace('}]', '}] as any;')

with open('lib/content/exercises/demystification.ts', 'w', encoding='utf-8') as f:
    f.write(typescript_content)
