import json
import re

exercises = []

# --- MODULE 12 : Le processeur physique (Hardware) ---
exercises.extend([
    {"id": "ex-mod12-1", "type": "quiz", "question": "Quelle est l'horloge la plus rapide du système ?", "difficulty": "easy", "xpReward": 20, "data": {"choices": [{"id": "a", "text": "L'horloge système (FSB/BCLK)."}, {"id": "b", "text": "L'horloge interne du CPU, obtenue par multiplication (Clock Multiplier) de l'horloge système."}, {"id": "c", "text": "L'horloge de la RAM."}], "correctId": "b", "explanation": "Le CPU tourne souvent à 4 GHz en multipliant l'horloge système de 100 MHz."}},
    {"id": "ex-mod12-2", "type": "quiz", "question": "Qu'est-ce que le MMIO (Memory-Mapped I/O) ?", "difficulty": "easy", "xpReward": 20, "data": {"choices": [{"id": "a", "text": "Une technique pour écrire sur le disque dur."}, {"id": "b", "text": "La carte graphique."}, {"id": "c", "text": "L'assignation de périphériques matériels (clavier, carte réseau) à des adresses mémoire spécifiques (RAM) pour communiquer avec eux via de simples 'mov'."}], "correctId": "c", "explanation": "Pour parler à un matériel MMIO, on écrit dans son 'adresse' comme si c'était de la RAM."}},
    {"id": "ex-mod12-3", "type": "quiz", "question": "Quel mot-clé C/C++ est OBLIGATOIRE lorsqu'on manipule des registres matériels MMIO ?", "difficulty": "medium", "xpReward": 30, "data": {"choices": [{"id": "a", "text": "inline"}, {"id": "b", "text": "volatile"}, {"id": "c", "text": "const"}], "correctId": "b", "explanation": "Il empêche le compilateur d'optimiser et de supprimer les lectures/écritures consécutives."}},
    {"id": "ex-mod12-4", "type": "fill-blank", "question": "Interruptions (IRQ)", "difficulty": "medium", "xpReward": 35, "data": {"codeTemplate": "; Avant de modifier le vecteur d'interruptions (IDT), on doit d'abord les désactiver\n__BLANK__ ; Clear Interrupt Flag\n; modification...\n__BLANK__ ; Set Interrupt Flag", "blanks": [{"id": "1", "answer": "cli", "hint": "Clear Interrupts."}, {"id": "2", "answer": "sti", "hint": "Set Interrupts."}], "explanation": "Sinon, une interruption pendant la modification provoquerait un crash instantané."}},
    {"id": "ex-mod12-5", "type": "quiz", "question": "Quelle pratique est formellement INTERDITE dans un gestionnaire d'interruption (ISR) ?", "difficulty": "medium", "xpReward": 30, "data": {"choices": [{"id": "a", "text": "Modifier une variable globale volatile."}, {"id": "b", "text": "Mettre une fonction de délai (ex: delay(1000)) ou appeler un syscall bloquant."}, {"id": "c", "text": "Allumer une LED."}], "correctId": "b", "explanation": "Un ISR bloque généralement toutes les autres interruptions. S'il est lent, le système 'freezera'."}},
    {"id": "ex-mod12-6", "type": "quiz", "question": "Qu'est-ce que le 'Pipeline' d'un CPU moderne ?", "difficulty": "hard", "xpReward": 50, "data": {"choices": [{"id": "a", "text": "Une technique d'exécution où les instructions sont découpées en plusieurs étapes (Fetch, Decode, Execute) exécutées en parallèle par différents circuits du CPU."}, {"id": "b", "text": "Un tuyau de refroidissement liquide."}, {"id": "c", "text": "Le câble d'alimentation."}], "correctId": "a", "explanation": "C'est l'équivalent d'une chaîne de montage d'usine. Une instruction sort à chaque cycle."}},
    {"id": "ex-mod12-7", "type": "drag-drop", "question": "Le Pipeline classique (RISC/CISC moderne)", "difficulty": "hard", "xpReward": 50, "data": {"items": [{"id": "1", "text": "Fetch (Récupérer l'instruction depuis le Cache L1)"}, {"id": "2", "text": "Decode (Décoder l'instruction en Micro-ops)"}, {"id": "3", "text": "Execute (L'ALU effectue le calcul)"}, {"id": "4", "text": "Write-Back (Écrire le résultat dans le registre)"}], "correctOrder": ["1", "2", "3", "4"], "instruction": "Ordonnez les étapes de traitement d'une seule instruction dans un processeur pipeliné.", "explanation": "Cette séparation permet au CPU de traiter 4 instructions en même temps à des étapes différentes."}},
    {"id": "ex-mod12-8", "type": "fill-blank", "question": "Superscalaire et IPC", "difficulty": "hard", "xpReward": 50, "data": {"codeTemplate": "; Un CPU superscalaire peut exécuter plus de 1 instruction par cycle.\n; Son IPC (Instructions Per Cycle) théorique dépend du nombre d'__BLANK__\n; (Unité Arithmétique et Logique).", "blanks": [{"id": "1", "answer": "ALU", "hint": "Arithmetic Logic Unit."}], "explanation": "S'il y a 4 ALU indépendantes, le processeur peut faire 4 additions en 1 seul cycle."}},
    {"id": "ex-mod12-9", "type": "quiz", "question": "Pourquoi le compilateur (ou le CPU lui-même via Out-of-Order Execution) réordonne-t-il vos instructions Assembleur ?", "difficulty": "hard", "xpReward": 50, "data": {"choices": [{"id": "a", "text": "Pour corriger vos bugs de logique."}, {"id": "b", "text": "Pour éviter les 'Data Hazards' (dépendances de données) qui forceraient le pipeline à faire une pause (stall)."}, {"id": "c", "text": "Pour le rendre illisible aux hackers."}], "correctId": "b", "explanation": "Si l'instruction 2 a besoin du résultat de l'instruction 1, le CPU peut avancer l'instruction 3 entre-temps."}},
    {"id": "ex-mod12-10", "type": "code-correction", "question": "Data Hazard Evitement", "difficulty": "hard", "xpReward": 50, "data": {"buggyCode": "add rax, rbx\nmov rcx, rax\nadd rdx, 5", "correctCode": "add rax, rbx\nadd rdx, 5\nmov rcx, rax", "hints": ["Éloignez l'utilisation de RAX de son calcul pour laisser le temps à l'ALU de finir."], "explanation": "Placer une instruction indépendante entre l'addition et la lecture du résultat masque la latence de l'addition."}}
])

# --- MODULE 13 : Les instructions SIMD ---
exercises.extend([
    {"id": "ex-mod13-1", "type": "quiz", "question": "Que signifie SIMD ?", "difficulty": "easy", "xpReward": 20, "data": {"choices": [{"id": "a", "text": "Single Instruction, Multiple Data."}, {"id": "b", "text": "System Internal Memory Device."}, {"id": "c", "text": "Simple Integer Math Divider."}], "correctId": "a", "explanation": "Une seule instruction assembleur exécute le même calcul sur plusieurs valeurs en même temps."}},
    {"id": "ex-mod13-2", "type": "quiz", "question": "Combien de bits fait un registre YMM (utilisé par AVX) ?", "difficulty": "easy", "xpReward": 20, "data": {"choices": [{"id": "a", "text": "64 bits"}, {"id": "b", "text": "128 bits"}, {"id": "c", "text": "256 bits"}], "correctId": "c", "explanation": "Un registre YMM de 256 bits peut contenir 8 entiers de 32 bits, ou 8 floats."}},
    {"id": "ex-mod13-3", "type": "quiz", "question": "Quelle est la principale source de plantages (crash) lors de l'utilisation manuelle d'instructions SIMD (SSE/AVX) avec la mémoire ?", "difficulty": "medium", "xpReward": 30, "data": {"choices": [{"id": "a", "text": "L'utilisation de nombres négatifs."}, {"id": "b", "text": "Une division par zéro."}, {"id": "c", "text": "Un mauvais alignement de la mémoire (ex: adresse non multiple de 16 ou 32 octets)."}], "correctId": "c", "explanation": "Les instructions comme 'movdqa' (Move Double Quadword Aligned) exigent un alignement strict, sinon c'est le crash garanti."}},
    {"id": "ex-mod13-4", "type": "fill-blank", "question": "Addition vectorielle (AVX)", "difficulty": "medium", "xpReward": 35, "data": {"codeTemplate": "; Additionner 8 floats simultanément\n; Le préfixe 'v' (VEX) permet une syntaxe non-destructrice à 3 opérandes\n__BLANK__ ymm0, ymm1, ymm2", "blanks": [{"id": "1", "answer": "vaddps", "hint": "Vector ADD Packed Single-precision."}], "explanation": "vaddps (AVX) additionne les éléments de ymm1 et ymm2 et met le résultat dans ymm0 sans écraser ymm1."}},
    {"id": "ex-mod13-5", "type": "quiz", "question": "Qu'est-ce que l'Auto-Vectorization ?", "difficulty": "medium", "xpReward": 30, "data": {"choices": [{"id": "a", "text": "Le fait que le CPU active AVX tout seul."}, {"id": "b", "text": "La capacité du compilateur (GCC, Clang) à analyser une boucle for classique et à la transformer automatiquement en instructions SIMD."}, {"id": "c", "text": "Un système de pilotage de voiture autonome."}], "correctId": "b", "explanation": "C'est l'optimisation (-O3) la plus redoutable. Le compilateur remplace votre boucle par une version 8 fois plus rapide."}},
    {"id": "ex-mod13-6", "type": "quiz", "question": "Quel est le risque de l'utilisation intensive des instructions AVX-512 (registres ZMM de 512 bits) ?", "difficulty": "hard", "xpReward": 50, "data": {"choices": [{"id": "a", "text": "La baisse de la fréquence d'horloge du processeur (Downclocking) à cause de la surchauffe extrême."}, {"id": "b", "text": "La suppression de Windows."}, {"id": "c", "text": "Le blocage de la carte graphique."}], "correctId": "a", "explanation": "Historiquement (Intel Skylake), exécuter des instructions AVX-512 consommait tellement d'énergie que le CPU baissait sa fréquence pour tout le monde."}},
    {"id": "ex-mod13-7", "type": "drag-drop", "question": "La hiérarchie des registres vectoriels SIMD", "difficulty": "hard", "xpReward": 50, "data": {"items": [{"id": "1", "text": "MMX (64 bits, partage les registres x87) - Obsolète"}, {"id": "2", "text": "SSE (XMM0-XMM15, 128 bits)"}, {"id": "3", "text": "AVX / AVX2 (YMM0-YMM15, 256 bits)"}, {"id": "4", "text": "AVX-512 (ZMM0-ZMM31, 512 bits)"}], "correctOrder": ["1", "2", "3", "4"], "instruction": "Classez les technologies SIMD de la plus ancienne/petite à la plus récente/grande.", "explanation": "Notez que la partie basse d'un registre YMM EST le registre XMM correspondant, tout comme EAX est dans RAX."}},
    {"id": "ex-mod13-8", "type": "fill-blank", "question": "Splatting / Broadcast", "difficulty": "hard", "xpReward": 50, "data": {"codeTemplate": "; Copier un seul float présent en mémoire dans TOUTES les positions d'un registre YMM (8 floats identiques)\n__BLANK__ ymm0, [ma_constante_float]", "blanks": [{"id": "1", "answer": "vbroadcastss", "hint": "Vector Broadcast Single Scalar."}], "explanation": "C'est vital pour multiplier tout un tableau de vecteurs par une seule constante (ex: augmenter la luminosité de tous les pixels)."}},
    {"id": "ex-mod13-9", "type": "quiz", "question": "Qu'est-ce qu'une opération 'Packed' vs 'Scalar' en SIMD ?", "difficulty": "hard", "xpReward": 50, "data": {"choices": [{"id": "a", "text": "Packed agit sur TOUS les éléments du registre simultanément. Scalar n'agit QUE sur le premier élément (le plus bas) du registre."}, {"id": "b", "text": "Packed compresse les données. Scalar les décompresse."}, {"id": "c", "text": "Aucune différence."}], "correctId": "a", "explanation": "Exemple : `addps` (Packed Single) additionne 4 floats. `addss` (Scalar Single) additionne seulement le 1er float et laisse les autres intacts."}},
    {"id": "ex-mod13-10", "type": "code-correction", "question": "Alignement SSE strict", "difficulty": "hard", "xpReward": 50, "data": {"buggyCode": "movups xmm0, [memoire_non_alignee]\nmovaps xmm1, [memoire_non_alignee]", "correctCode": "movups xmm0, [memoire_non_alignee]\nmovups xmm1, [memoire_non_alignee]", "hints": ["L'instruction 'aps' (Aligned Packed Single) crashera si la mémoire n'est pas alignée sur 16 octets."], "explanation": "Si vous n'êtes pas certain de l'alignement, utilisez toujours la version Unaligned (movups, vmovups). Avec AVX, la pénalité de performance de l'Unaligned est devenue quasi-nulle."}}
])

# --- MODULE 14 : Les Conventions d'Appel (ABI) ---
exercises.extend([
    {"id": "ex-mod14-1", "type": "quiz", "question": "Sous System V ABI (Linux x86-64), dans quel ordre sont passés les 6 premiers arguments entiers d'une fonction ?", "difficulty": "easy", "xpReward": 20, "data": {"choices": [{"id": "a", "text": "Sur la pile, de droite à gauche."}, {"id": "b", "text": "RDI, RSI, RDX, RCX, R8, R9"}, {"id": "c", "text": "RAX, RBX, RCX, RDX, RDI, RSI"}], "correctId": "b", "explanation": "Cette séquence est utilisée universellement sur Linux/macOS."}},
    {"id": "ex-mod14-2", "type": "quiz", "question": "Où passe-t-on le 7ème argument d'une fonction sous Linux x86-64 ?", "difficulty": "easy", "xpReward": 20, "data": {"choices": [{"id": "a", "text": "Dans R10."}, {"id": "b", "text": "Sur la pile (Stack), poussé avant l'appel."}, {"id": "c", "text": "On ne peut pas avoir 7 arguments."}], "correctId": "b", "explanation": "Une fois les registres épuisés, on utilise le mécanisme historique : la pile."}},
    {"id": "ex-mod14-3", "type": "quiz", "question": "Quelle est la particularité très stricte de l'ABI Windows x64 concernant le 'Shadow Space' ?", "difficulty": "medium", "xpReward": 30, "data": {"choices": [{"id": "a", "text": "L'appelant (caller) DOIT allouer systématiquement 32 octets sur la pile avant chaque 'call', même si la fonction n'a aucun argument."}, {"id": "b", "text": "Les ombres ne sont pas gérées par le CPU."}, {"id": "c", "text": "L'appelé (callee) doit vider le cache."}], "correctId": "a", "explanation": "Ces 32 octets servent de zone de sauvegarde (Home Space) pour que la fonction appelée puisse y déverser RCX/RDX/R8/R9 si elle a besoin de les utiliser."}},
    {"id": "ex-mod14-4", "type": "fill-blank", "question": "Registres Volatils vs Non-Volatils", "difficulty": "medium", "xpReward": 35, "data": {"codeTemplate": "; La fonction appelée DOIT restaurer certains registres (Non-Volatils) avant de revenir.\n; Exemple type sur Linux :\npush __BLANK__\n; ... utilisation ...\npop __BLANK__\nret", "blanks": [{"id": "1", "answer": "rbx", "hint": "Registre Base."}, {"id": "2", "answer": "rbx", "hint": "Restauration."}], "explanation": "RBX, RBP, R12-R15 sont Callee-Saved (non-volatils). RDI, RSI, RAX, RCX sont Caller-Saved (volatils)."}},
    {"id": "ex-mod14-5", "type": "quiz", "question": "Comment retourne-t-on un gros objet C++ (ex: un struct de 128 octets) qui ne rentre pas dans RAX ?", "difficulty": "medium", "xpReward": 30, "data": {"choices": [{"id": "a", "text": "L'appelant alloue l'espace mémoire pour l'objet et passe un pointeur 'caché' (souvent dans RDI) à l'appelé pour qu'il le remplisse (Return Value Optimization)."}, {"id": "b", "text": "On le retourne via la carte graphique."}, {"id": "c", "text": "On utilise R8, R9, R10 et R11 simultanément."}], "correctId": "a", "explanation": "L'objet n'est techniquement jamais 'retourné', il est construit 'sur place' directement dans la Frame de l'appelant."}},
    {"id": "ex-mod14-6", "type": "quiz", "question": "Pourquoi la convention d'appel 'fastcall' a-t-elle été inventée à l'époque du 32-bits (x86) ?", "difficulty": "hard", "xpReward": 50, "data": {"choices": [{"id": "a", "text": "Parce qu'à l'origine (cdecl), TOUS les arguments passaient par la pile (très lent). Fastcall passait les 2 ou 3 premiers dans ECX/EDX."}, {"id": "b", "text": "Pour faire des sauts plus loin."}, {"id": "c", "text": "Pour exécuter le programme plus vite."}], "correctId": "a", "explanation": "Le passage par registre est immensément plus rapide que les push/pop sur la pile."}},
    {"id": "ex-mod14-7", "type": "drag-drop", "question": "Différence Linux vs Windows x64", "difficulty": "hard", "xpReward": 50, "data": {"items": [{"id": "1", "text": "Arguments Windows"}, {"id": "2", "text": "Arguments Linux"}, {"id": "3", "text": "Shadow Space Windows"}, {"id": "4", "text": "Red Zone Linux (128 octets sous RSP)"}], "correctOrder": ["1", "2", "3", "4"], "instruction": "Associez les concepts. Mettez d'abord Windows (Args: RCX, RDX, R8, R9), puis Linux (Args: RDI, RSI...), puis Shadow Space (32 octets obligatoires pour Win), puis Red Zone (Zone sûre de 128 bytes pour Linux).", "explanation": "La Red Zone Linux permet aux fonctions feuilles (leaf functions) d'utiliser la pile sans même bouger RSP !"}},
    {"id": "ex-mod14-8", "type": "fill-blank", "question": "Nettoyage de pile de l'Appelant", "difficulty": "hard", "xpReward": 50, "data": {"codeTemplate": "push rdx ; Arg 8\npush rcx ; Arg 7\ncall grosse_fonction\n; L'appelant doit restaurer la pile !\nadd rsp, __BLANK__", "blanks": [{"id": "1", "answer": "16", "hint": "2 push de 8 octets."}], "explanation": "Sous cdecl/SystemV, c'est celui qui appelle (Caller) qui a la responsabilité de retirer les arguments de la pile après le 'call'."}},
    {"id": "ex-mod14-9", "type": "quiz", "question": "Qu'est-ce que la 'Name Mangling' (Décoration de nom) en C++ ?", "difficulty": "hard", "xpReward": 50, "data": {"choices": [{"id": "a", "text": "Le compilateur modifie le nom d'une fonction (ex: void func(int) devient _Z4funci) pour encoder ses paramètres, permettant la surcharge (Overloading)."}, {"id": "b", "text": "L'ajout d'emojis dans les commentaires."}, {"id": "c", "text": "La suppression des variables."}], "correctId": "a", "explanation": "C'est pour cela qu'on utilise `extern \"C\"` : pour désactiver le Mangling et garder le nom pur afin d'être appelé depuis l'Assembleur ou le C."}},
    {"id": "ex-mod14-10", "type": "code-correction", "question": "Alignement de la pile à 16 octets", "difficulty": "hard", "xpReward": 50, "data": {"buggyCode": "; On appelle printf sans aligner la pile\npush rax ; La pile est maintenant désalignée (terminant par 8)\nmov rdi, chaine\ncall printf", "correctCode": "sub rsp, 8 ; Aligner la pile sur 16 octets\npush rax ; 8 + 8 = 16\nmov rdi, chaine\ncall printf\nadd rsp, 16 ; Nettoyage", "hints": ["La pile DOIT être alignée sur 16 octets avant d'appeler une fonction C."], "explanation": "La glibc Linux utilise des instructions AVX qui crashent lamentablement (Segfault) si la pile n'est pas un multiple de 16 au moment du CALL."}}
])

# --- MODULE 15 : La FPU & les Structures Memoires ---
exercises.extend([
    {"id": "ex-mod15-1", "type": "quiz", "question": "Sur les processeurs modernes, quels registres utilise-t-on pour les calculs en virgule flottante (Float/Double) ?", "difficulty": "easy", "xpReward": 20, "data": {"choices": [{"id": "a", "text": "Les registres SSE/AVX (XMM, YMM)."}, {"id": "b", "text": "L'ancien coprocesseur x87 (ST0-ST7)."}, {"id": "c", "text": "Les registres généraux (RAX)."}], "correctId": "a", "explanation": "Le x87 est obsolète. Les compilateurs utilisent le jeu d'instructions SSE (XMM) pour faire des mathématiques flottantes scalaires."}},
    {"id": "ex-mod15-2", "type": "quiz", "question": "Pourquoi le compilateur ajoute-t-il du 'Padding' (octets vides) dans une structure C ?", "difficulty": "easy", "xpReward": 20, "data": {"choices": [{"id": "a", "text": "Pour aligner les variables en mémoire et accélérer les accès CPU."}, {"id": "b", "text": "Pour cacher des virus."}, {"id": "c", "text": "Pour détecter les Buffer Overflows."}], "correctId": "a", "explanation": "Un entier 32-bits doit idéalement commencer à une adresse multiple de 4."}},
    {"id": "ex-mod15-3", "type": "quiz", "question": "Dans quel registre passe-t-on le premier argument 'float' ou 'double' à une fonction sous Linux x86-64 ?", "difficulty": "medium", "xpReward": 30, "data": {"choices": [{"id": "a", "text": "XMM0"}, {"id": "b", "text": "RDI"}, {"id": "c", "text": "ST0"}], "correctId": "a", "explanation": "Les entiers vont dans RDI/RSI..., les floats dans XMM0/XMM1... Ils utilisent des chemins matériels différents."}},
    {"id": "ex-mod15-4", "type": "fill-blank", "question": "L'instruction Flottante Scalaire", "difficulty": "medium", "xpReward": 35, "data": {"codeTemplate": "; Additionner deux doubles (64-bits flottant) dans XMM0\n__BLANK__ xmm0, xmm1", "blanks": [{"id": "1", "answer": "addsd", "hint": "ADD Scalar Double-precision."}], "explanation": "Suffixes : 'ss' = Scalar Single (float 32), 'sd' = Scalar Double (double 64). 'ps' = Packed Single, 'pd' = Packed Double."}},
    {"id": "ex-mod15-5", "type": "quiz", "question": "Combien d'octets pèse cette structure (sans la forcer avec __attribute__((packed))) : `struct { char a; int b; char c; }` sur 64-bits ?", "difficulty": "medium", "xpReward": 30, "data": {"choices": [{"id": "a", "text": "6 octets"}, {"id": "b", "text": "12 octets"}, {"id": "c", "text": "16 octets"}], "correctId": "b", "explanation": "a(1) + padding(3) + b(4) + c(1) + padding final(3) = 12. Le compilateur ajoute du padding interne et un padding de fin pour l'alignement."}},
    {"id": "ex-mod15-6", "type": "quiz", "question": "Quel est le danger d'utiliser `__attribute__((packed))` sur une structure ?", "difficulty": "hard", "xpReward": 50, "data": {"choices": [{"id": "a", "text": "Le CPU devra faire deux lectures mémoire au lieu d'une pour récupérer un entier désaligné, plombant les performances (voire crash sur ARM)."}, {"id": "b", "text": "La structure prendra plus de RAM."}, {"id": "c", "text": "Elle deviendra illisible en C."}], "correctId": "a", "explanation": "Le packing est réservé à la lecture stricte de formats de fichiers ou de paquets réseau bruts."}},
    {"id": "ex-mod15-7", "type": "drag-drop", "question": "Format IEEE 754 (Float 32-bits)", "difficulty": "hard", "xpReward": 50, "data": {"items": [{"id": "1", "text": "Signe (1 bit - positif/négatif)"}, {"id": "2", "text": "Exposant (8 bits - Puissance de 2 avec biais de 127)"}, {"id": "3", "text": "Mantisse / Fraction (23 bits - les décimales du nombre)"}], "correctOrder": ["1", "2", "3"], "instruction": "Ordonnez les éléments composant un nombre flottant (de la gauche vers la droite / bit de poids fort vers faible).", "explanation": "C'est la norme mathématique hardware utilisée par absolument tous les CPU modernes pour la virgule flottante."}},
    {"id": "ex-mod15-8", "type": "fill-blank", "question": "Conversion Entier -> Float", "difficulty": "hard", "xpReward": 50, "data": {"codeTemplate": "; Convertir l'entier 32-bits dans EAX vers un Float 32-bits dans XMM0\n__BLANK__ xmm0, eax", "blanks": [{"id": "1", "answer": "cvtsi2ss", "hint": "ConVerT Scalar Integer TO Scalar Single."}], "explanation": "Le CPU a des instructions dédiées pour changer le codage binaire entre la représentation entière (Complément à 2) et la norme IEEE 754."}},
    {"id": "ex-mod15-9", "type": "quiz", "question": "Quelle valeur RAX doit-il avoir avant d'appeler `printf` sous Linux s'il n'y a pas de variables float (variadic args) ?", "difficulty": "hard", "xpReward": 50, "data": {"choices": [{"id": "a", "text": "RAX doit contenir le nombre de registres XMM utilisés (donc 0)."}, {"id": "b", "text": "RAX doit valoir 1."}, {"id": "c", "text": "Peu importe."}], "correctId": "a", "explanation": "Pour les fonctions à arguments variables (comme printf), l'ABI impose d'indiquer combien de registres vectoriels contiennent des paramètres, pour éviter des sauvegardes inutiles."}},
    {"id": "ex-mod15-10", "type": "code-correction", "question": "Struct réorganisation", "difficulty": "hard", "xpReward": 50, "data": {"buggyCode": "struct Data {\n  char a;\n  double b;\n  char c;\n};", "correctCode": "struct Data {\n  double b; // 8 bytes\n  char a;   // 1 byte\n  char c;   // 1 byte\n};", "hints": ["Regroupez les types similaires et placez les plus gros en premier pour réduire le padding final."], "explanation": "La 1ère version prend 24 octets (1+7pad + 8 + 1+7pad). La 2ème version prend 16 octets (8 + 1 + 1 + 6pad). Une économie massive !"}}
])

# --- MODULE 16 : Securité & Exploitation ---
exercises.extend([
    {"id": "ex-mod16-1", "type": "quiz", "question": "Dans un Buffer Overflow classique (Smashing the stack), quelle valeur de la pile l'attaquant cherche-t-il spécifiquement à écraser ?", "difficulty": "easy", "xpReward": 20, "data": {"choices": [{"id": "a", "text": "La 'Return Address' (Adresse de Retour) poussée par le call précédent."}, {"id": "b", "text": "Le registre RAX."}, {"id": "c", "text": "Les paramètres de la fonction."}], "correctId": "a", "explanation": "En écrasant cette adresse, l'instruction 'ret' finale forcera le processeur à sauter vers l'adresse choisie par l'attaquant."}},
    {"id": "ex-mod16-2", "type": "quiz", "question": "Qu'est-ce qu'un NOP Sled (Toboggan à NOPs) ?", "difficulty": "easy", "xpReward": 20, "data": {"choices": [{"id": "a", "text": "Une suite d'instructions NOP (0x90) placée avant le code malveillant pour augmenter les chances de réussite de l'exploitation."}, {"id": "b", "text": "Un jeu d'hiver."}, {"id": "c", "text": "Une technique d'optimisation du CPU."}], "correctId": "a", "explanation": "Si le saut atterrit n'importe où dans le NOP Sled, le processeur glissera pacifiquement (NOP = Ne Rien Faire) jusqu'au Shellcode."}},
    {"id": "ex-mod16-3", "type": "quiz", "question": "Qu'est-ce que le Shellcode ?", "difficulty": "medium", "xpReward": 30, "data": {"choices": [{"id": "a", "text": "Du code en langage C."}, {"id": "b", "text": "Des opcodes binaires d'Assembleur bruts injectés dans la RAM cible (généralement conçus pour ouvrir un terminal/shell)."}, {"id": "c", "text": "Un script Bash."}], "correctId": "b", "explanation": "C'est l'essence de l'exploitation : injecter le Payload (instructions machine) sous forme de chaîne de caractères via une faille."}},
    {"id": "ex-mod16-4", "type": "fill-blank", "question": "Protection NX Bit (No eXecute)", "difficulty": "medium", "xpReward": 35, "data": {"codeTemplate": "; Le bit NX empêche matériellement l'exécution d'instructions situées sur la __BLANK__ ou le Tas.\n; Un buffer overflow classique (sauter sur son propre shellcode) lèvera une exception matérielle.", "blanks": [{"id": "1", "answer": "pile", "hint": "Stack."}], "explanation": "Cette protection (Data Execution Prevention - DEP) rend la mémoire inscriptible non-exécutable."}},
    {"id": "ex-mod16-5", "type": "quiz", "question": "Comment l'attaque ROP (Return-Oriented Programming) contourne-t-elle le NX Bit ?", "difficulty": "medium", "xpReward": 30, "data": {"choices": [{"id": "a", "text": "Elle modifie les droits du NX bit."}, {"id": "b", "text": "Au lieu d'injecter du code, elle écrase la pile avec une succession d'adresses pointant vers des bouts de code légitime existant (Gadgets) se terminant par 'ret'."}, {"id": "c", "text": "Elle infecte le BIOS."}], "correctId": "b", "explanation": "En chaînant des 'ret', l'attaquant programme le processeur à sauter de gadget en gadget dans le code original de l'application (ou de la libc)."}},
    {"id": "ex-mod16-6", "type": "quiz", "question": "Qu'est-ce que l'ASLR (Address Space Layout Randomization) ?", "difficulty": "hard", "xpReward": 50, "data": {"choices": [{"id": "a", "text": "L'OS charge aléatoirement les adresses de base du code, de la pile et des bibliothèques à chaque lancement, rendant l'attaque ROP extrêmement difficile."}, {"id": "b", "text": "Un algorithme de chiffrement de la RAM."}, {"id": "c", "text": "Le fait que les pointeurs C changent de type."}], "correctId": "a", "explanation": "Sans adresse fixe connue, l'attaquant ne sait plus quelle valeur écrire pour écraser la Return Address vers son gadget."}},
    {"id": "ex-mod16-7", "type": "drag-drop", "question": "Anatomie d'une attaque ROP", "difficulty": "hard", "xpReward": 50, "data": {"items": [{"id": "1", "text": "Le programme lit une entrée utilisateur (buffer overflow via gets())"}, {"id": "2", "text": "L'attaquant écrase les variables, puis le RBP, puis la Return Address sur la pile"}, {"id": "3", "text": "La Return Address est remplacée par l'adresse du 1er Gadget (ex: pop rdi ; ret)"}, {"id": "4", "text": "Le 'ret' du gadget fait dépiler la valeur suivante (paramètre /bin/sh) dans RDI, puis saute au 2ème gadget"}], "correctOrder": ["1", "2", "3", "4"], "instruction": "Déroulez la chaîne d'exécution mortelle d'un ROP Chain.", "explanation": "C'est l'attaque la plus sophistiquée et la plus courante de la dernière décennie."}},
    {"id": "ex-mod16-8", "type": "fill-blank", "question": "Le Stack Canary", "difficulty": "hard", "xpReward": 50, "data": {"codeTemplate": "; Le compilateur génère une valeur secrète (le Canari) entre le buffer et l'adresse de retour.\n; À la fin de la fonction, il vérifie si le canari a été modifié :\nmov rax, [rbp - 8] ; Charger le canari local\n__BLANK__ rax, fs:0x28 ; Comparer avec le canari original de l'OS\njne stack_chk_fail", "blanks": [{"id": "1", "answer": "cmp", "hint": "Instruction de comparaison."}], "explanation": "Si un Buffer Overflow se produit, il écrasera inévitablement le Canari avant d'atteindre la Return Address. La fonction s'en rendra compte et plantera intentionnellement."}},
    {"id": "ex-mod16-9", "type": "quiz", "question": "Que cherche à faire un 'Format String Attack' (ex: printf(user_input)) ?", "difficulty": "hard", "xpReward": 50, "data": {"choices": [{"id": "a", "text": "À faire crasher le terminal de l'utilisateur."}, {"id": "b", "text": "À utiliser `%x` pour divulguer la mémoire de la pile (leak) et `%n` pour écrire arbitrairement n'importe où en mémoire, contournant souvent le Canari et l'ASLR."}, {"id": "c", "text": "À insérer des caractères invisibles."}], "correctId": "b", "explanation": "C'est une faille terrifiante permettant lecture ET écriture absolues depuis une simple erreur de la fonction printf."}},
    {"id": "ex-mod16-10", "type": "code-correction", "question": "Fix Buffer Overflow C", "difficulty": "hard", "xpReward": 50, "data": {"buggyCode": "void login() {\n  char buffer[32];\n  gets(buffer);\n}", "correctCode": "void login() {\n  char buffer[32];\n  fgets(buffer, 32, stdin);\n}", "hints": ["La fonction gets() ne vérifie JAMAIS la taille de ce qu'elle lit."], "explanation": "L'utilisation de gets() est le cas d'école numéro 1 des Buffer Overflows. Toujours utiliser des fonctions sûres bornées par la taille (fgets, strncpy)."}}
])

# --- MODULE 17 : Le Bootloader & Ring 0 ---
exercises.extend([
    {"id": "ex-mod17-1", "type": "quiz", "question": "Quelle est la contrainte principale d'un bootloader BIOS (stage 1) logé dans le MBR ?", "difficulty": "easy", "xpReward": 20, "data": {"choices": [{"id": "a", "text": "Il ne fait que 512 octets et le CPU démarre en mode réel 16-bits."}, {"id": "b", "text": "Il doit être écrit en Java."}, {"id": "c", "text": "Il n'a pas accès au clavier."}], "correctId": "a", "explanation": "Pour des raisons de rétrocompatibilité (8086), le processeur de votre PC moderne à 4000€ démarre TOUJOURS comme un CPU des années 80."}},
    {"id": "ex-mod17-2", "type": "quiz", "question": "Quels sont les deux octets magiques (Magic Signature) obligatoires à la fin des 512 octets du MBR pour que le BIOS accepte de l'exécuter ?", "difficulty": "easy", "xpReward": 20, "data": {"choices": [{"id": "a", "text": "0x55 0xAA"}, {"id": "b", "text": "0xFF 0xFF"}, {"id": "c", "text": "0xDE 0xAD"}], "correctId": "a", "explanation": "Le BIOS lit le secteur 0 du disque. S'il ne se termine pas par 0xAA55, il affiche 'No bootable device'."}},
    {"id": "ex-mod17-3", "type": "quiz", "question": "Qu'est-ce que le 'Mode Protégé' (Protected Mode) du CPU ?", "difficulty": "medium", "xpReward": 30, "data": {"choices": [{"id": "a", "text": "Un mode anti-virus."}, {"id": "b", "text": "Le mode 32-bits (ou 64-bits) activé par le kernel, permettant la mémoire virtuelle, les privilèges Ring 0/Ring 3, et la protection de la mémoire (MMU)."}, {"id": "c", "text": "Le mode où le code est caché."}], "correctId": "b", "explanation": "Le passage du Mode Réel 16-bits au Mode Protégé est la tâche la plus critique d'un bootloader moderne."}},
    {"id": "ex-mod17-4", "type": "fill-blank", "question": "Le Registre CR0", "difficulty": "medium", "xpReward": 35, "data": {"codeTemplate": "; Pour basculer du Mode Réel au Mode Protégé 32-bits,\n; on met à 1 le bit PE (Protection Enable) du registre Control Register 0.\nmov eax, cr0\nor eax, 1\nmov __BLANK__, eax", "blanks": [{"id": "1", "answer": "cr0", "hint": "Le même registre."}], "explanation": "CR0 est le registre système central (et secret) qui configure l'état du CPU."}},
    {"id": "ex-mod17-5", "type": "quiz", "question": "Que sont les anneaux de privilège (Rings) x86 ?", "difficulty": "medium", "xpReward": 30, "data": {"choices": [{"id": "a", "text": "Des cercles de mémoire RAM."}, {"id": "b", "text": "Des niveaux d'accès matériel : Ring 0 pour le Noyau (OS) avec accès total, Ring 3 pour les applications utilisateur (limitées)."}, {"id": "c", "text": "Les différents cœurs du processeur."}], "correctId": "b", "explanation": "Une application utilisateur (Ring 3) ne peut pas utiliser des instructions dangereuses comme 'cli' ou lire la RAM d'un autre programme."}},
    {"id": "ex-mod17-6", "type": "quiz", "question": "Quelle est la fonction d'une GDT (Global Descriptor Table) dans le bootloader ?", "difficulty": "hard", "xpReward": 50, "data": {"choices": [{"id": "a", "text": "Elle définit les segments de mémoire pour l'OS, avec leurs droits d'accès (Code, Données, Ring 0, Ring 3) requis pour le Mode Protégé."}, {"id": "b", "text": "Elle contient les polices d'écran."}, {"id": "c", "text": "Elle gère le réseau."}], "correctId": "a", "explanation": "Sans GDT chargée (via l'instruction 'lgdt'), le processeur refuse de passer en 32/64 bits."}},
    {"id": "ex-mod17-7", "type": "drag-drop", "question": "La séquence de Démarrage (Boot Process)", "difficulty": "hard", "xpReward": 50, "data": {"items": [{"id": "1", "text": "Mise sous tension, le CPU exécute le BIOS/UEFI"}, {"id": "2", "text": "Le BIOS charge les 512 octets du MBR (Bootloader Stage 1) en mémoire réelle"}, {"id": "3", "text": "Le Stage 1 charge le Stage 2 (ex: GRUB) depuis le disque"}, {"id": "4", "text": "Le Stage 2 charge le Kernel Linux en mémoire, configure la GDT et passe en Mode Protégé (Ring 0)"}], "correctOrder": ["1", "2", "3", "4"], "instruction": "Déroulez les étapes du Big Bang d'un ordinateur.", "explanation": "C'est l'escalade des privilèges et des capacités depuis le monde archaïque 16-bits jusqu'au monde moderne."}},
    {"id": "ex-mod17-8", "type": "fill-blank", "question": "Accès VGA direct (Bare Metal)", "difficulty": "hard", "xpReward": 50, "data": {"codeTemplate": "; En Ring 0 Bare Metal, il n'y a pas de fonction 'printf'.\n; Pour afficher un caractère sur l'écran en mode texte couleur,\n; on écrit directement dans la mémoire vidéo mappée à l'adresse 0xB8000.\nmov byte [__BLANK__], 'A' ; Le caractère ASCII\nmov byte [__BLANK__ + 1], 0x0F ; Le style (Blanc brillant)", "blanks": [{"id": "1", "answer": "0xB8000", "hint": "L'adresse magique de la RAM vidéo texte."}, {"id": "2", "answer": "0xB8000", "hint": "Le byte suivant."}], "explanation": "C'est le MMIO pur. Chaque caractère à l'écran prend 2 octets : le code ASCII et les métadonnées de couleur."}},
    {"id": "ex-mod17-9", "type": "quiz", "question": "Pourquoi la création d'un OS 64-bits 'Bare Metal' aujourd'hui utilise-t-elle souvent UEFI plutôt que le BIOS (MBR) ?", "difficulty": "hard", "xpReward": 50, "data": {"choices": [{"id": "a", "text": "UEFI démarre directement en 32/64 bits, évitant le cauchemar du Mode Réel 16-bits, et fournit des services C/C++ de haut niveau pour le bootloader."}, {"id": "b", "text": "C'est moins cher."}, {"id": "c", "text": "L'UEFI est open-source."}], "correctId": "a", "explanation": "L'UEFI a tué le MBR pour la simple et bonne raison qu'il vous permet d'écrire votre bootloader (Bootmgfw.efi) en langage C moderne sans toucher à l'assembleur 16-bits."}},
    {"id": "ex-mod17-10", "type": "code-correction", "question": "Le Far Jump", "difficulty": "hard", "xpReward": 50, "data": {"buggyCode": "; Après avoir activé CR0 pour le Mode Protégé, il faut vider le pipeline 16-bits.\njmp protected_mode_start", "correctCode": "jmp 0x08:protected_mode_start\n; (0x08 est le sélecteur de Segment de Code dans la GDT)", "hints": ["Un saut local (near) garde l'ancien segment 16-bits. Il faut un saut lointain (far jump) avec le sélecteur GDT."], "explanation": "Ce fameux Far Jump magique est la toute dernière étape du bootloader pour basculer définitivement le processeur dans sa nouvelle ère 32/64 bits."}}
])


# Write out the file
typescript_content = f"""import {{ Exercise, QuizData, FillBlankData, DragDropData, InteractiveLabData, CodeCorrectionData }} from '../../types';

export const advancedExercises: Exercise[] = {json.dumps(exercises, indent=2)};
"""

# Type casting
import re
typescript_content = re.sub(r'(\s+)"data": ({{.*?}})', r'\1"data": \2 as any', typescript_content, flags=re.DOTALL)

with open('lib/content/exercises/advanced.ts', 'w', encoding='utf-8') as f:
    f.write(typescript_content)

print("Created 60 advanced exercises successfully!")
